### ISSUE TITLE
Cannot find module 'cordova-plugin-firebase-messaging'.

### ISSUE THREAD

**Issue by maxhsantos** [chemerisuk/cordova-plugin-firebase-messaging#100]
Hi, i'm try add plugin in my ionic project but i can't. How can i import from my project? 
Usually run add "name-plugin' its ok. I run cordova plugin add cordova-plugin-firebase-messaging, but my project can't find this module.
![Captura de Tela 2019-07-03 às 17 55 59 (2)](https://user-images.githubusercontent.com/13007611/60627398-f5cfeb00-9dbb-11e9-905e-759058fdb948.png)

**Comment by WolftechBroadcastSolutions** [comment]
Looks like you are using Ionic and not adding the plugin correctly. You need to also install the ionic-native wrapper and include it like this:

import { FirebaseMessaging } from '@ionic-native/firebase-messaging/ngx';

Ionic docs:
https://ionicframework.com/docs/native/firebase-messaging#usage

**Comment by maxhsantos** [comment]
thanks :D
