### ISSUE TITLE
iOS notifications not working, only token function.

### ISSUE THREAD

**Issue by CesarGalindoSalgado** [chemerisuk/cordova-plugin-firebase-messaging#101]
Hello, I'm having the same issue with my project. Everything compiles and run perfectly. I can allow the notifications using the suggested function, I can get token, but I don't receive any notifications, foreground neither background. I would like to know if for ios, using this library, we still need to create the certificate to allow notifications or to do other steps in order to get notifications, I tried to print in console but nothing and I tested sending msg using my own server and the console, both perfectly worked on android. I didn't have issues in android. Is there a way to know where my project is failing?. I'm running cordova 9.0.0, ios 5.0.0, xcode 10.2.1, node 10.16.0. thanks in advance.

**Comment by edwardbrosens** [comment]
I'm having same problem, onMessage and onBackgroundMessage are not being called anymore.

**Comment by chemerisuk** [comment]
Post all plugin names you have in the project.

**Comment by edwardbrosens** [comment]
cordova-android-support-gradle-release
cordova-call
cordova-plugin-app-version
cordova-plugin-background-mode
cordova-plugin-device
cordova-plugin-dialogs
cordova-plugin-firebase-messaging
cordova-plugin-geolocation
cordova-plugin-googlemaps
cordova-plugin-insomnia
cordova-plugin-ionic-keyboard
cordova-plugin-ionic-webview
cordova-plugin-mauron85-background-geolocation
cordova-plugin-opentok
cordova-plugin-screen-orientation
cordova-plugin-splashscreen
cordova-plugin-statusbar
cordova-plugin-whitelist
cordova-sqlite-storage
cordova-support-android-plugin
cordova-support-google-services
es6-promise-plugin
mx.ferreyra.callnumber

**Comment by chemerisuk** [comment]
@edwardbrosens have you checked on a real device?

**Comment by edwardbrosens** [comment]
> @edwardbrosens have you checked on a real device?

Yes I did, because on emulator it's not supported.
Problem is it worked before. And now it doesn't. 
I'm keeping in mind that it might have something todo with an iOS update or something I changed in code. I've found nothing odd so far.

**Comment by CesarGalindoSalgado** [comment]
Hello @chemerisuk  I'm testing only with this plugin, nothing else. I was thinking that maybe some kind of certificate or firebase configuration is missing. I saw at firebase something called apns and too many tutorials that teach you how to enable push notifications using the apple web developer with certificates, is that needed?.
thanks in advance

**Comment by edwardbrosens** [comment]
So, I do receive normal notifications.
But in my app the onMessage and onBackgroundMessage are not being called.

Also this appears in the logs:
`The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.`

And this:
`FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging`

Does it have anything to do with this issue?

**Comment by edwardbrosens** [comment]
Okay I've tried different versions.
`- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo` is not triggered on silent notifications
And
`- (void)postNotification:(NSDictionary*)userInfo background:(BOOL)background`
also not triggered.

**Comment by edwardbrosens** [comment]
Fixed it: turns out I have to add
`"content-available": 1`
to the message.
https://stackoverflow.com/questions/37570200/firebase-silent-apns-notification

**Comment by CesarGalindoSalgado** [comment]
Hi @edwardbrosens, did you configure APNS Certificate and turn on push notifications in the apple developer site?

**Comment by claudiulazar** [comment]
Hi @edwardbrosens, what was the solution in the end?
I have enabled push notification from the developer.apple site and everything is the project and I have the capability of push notification added. But the notification aren't coming when I am firing them from the firebase console. (on android it works)

**Comment by CesarGalindoSalgado** [comment]
Hi @claudiulazar  I have tried the configuration as you suggested, but I can not generate the file .p12 just the .p8 but I don't know where to find the 2 other IDs it asks.
What I understood from @edwardbrosens  is that now he has to put an extra flag in the json. But I don't know if he configured everything on firebase.

**Comment by claudiulazar** [comment]
@CesarGalindoSalgado I managed to send notifications to iOS, you just need to install correctly the certificates.
follow the exact steps from here and add the p12 not the p8 which you can download when you create the key try following this tutorial 
https://firebase.google.com/docs/cloud-messaging/ios/certs

To generate the p12 file:

1. - Download the certificate from the developer.apple site (ex: aps_development.cer).
2. - Open the file with Keychain Access app (double click on the cer file)
3. - Select Certificates in the Category from the left side menu.
4. - Find your certificate, right click on it and click export.
5. - Select the .p12 extension, add a password which you will have to enter in the firebase console.

And now try to send a notification.

**Comment by CesarGalindoSalgado** [comment]
@claudiulazar  I will do it right now

**Comment by edwardbrosens** [comment]
> Hi @edwardbrosens, what was the solution in the end?
> I have enabled push notification from the developer.apple site and everything is the project and I have the capability of push notification added. I connected the apple developer account with the firebase console. But the notification aren't coming when I am firing them from the firebase console. (on android it works)
> Logging the receive data from subscribing to the onMessage and onBackgroundMessage doesn't print anything on iOS, but on android, works perfectly.
> Thanks in advance
> 
> @CesarGalindoSalgado normally you should connect the apple developer account with the firebase in order for the apple notification center to permit firebase to give them the notifications you want to show.

Sorry for the late answer.
I was able to send notifications via the dashboard.
The problem was that so called silent notifications a.k.a data only notifications didn't come through.

**Comment by edwardbrosens** [comment]
> Hi @claudiulazar I have tried the configuration as you suggested, but I can not generate the file .p12 just the .p8 but I don't know where to find the 2 other IDs it asks.
> What I understood from @edwardbrosens is that now he has to put an extra flag in the json. But I don't know if he configured everything on firebase.

Everything is configured correctly on Firebase.
But there are two types of notifications.
To make sure you've set up the certificates correctly try to send a via the Dashboard (firebase), I you receive it on both platforms then it's working.

But if you want to send messages from your own backend application/service you can also send silent notifications. Those are useful if you want to send data to a device without showing an actual notification in de notification drawer or message center. 
I was having trouble getting that to work until I found out I was missing a flag I had to set.

**Comment by mobilestar2015** [comment]
I was facing similar issue that didn't receive any notifications.
I set "content_available" option but didn't receive notifications.
My issue was that it requires to call 'requestPermission' method but I didn't call that method.
I hope this helps others who is experiencing similar issue.

**Comment by CesarGalindoSalgado** [comment]
Thanks @claudiulazar , my issue was with the firebase configuration. 
thanks @edwardbrosens for your support

**Comment by dbessa1** [comment]
eu tenho exatamente o mesmo problema

**Comment by yashdabi** [comment]
@mobilestar2015 thanks, you are a superhero
I didn't know about "requestPermission"

**Comment by DuaneQ** [comment]
> https://stackoverflow.com/questions/37570200/firebase-silent-apns-notification

Do you mean content_available has to be apart of the payload?

`    const payload = {
        content_available: 1,
        notification: {
            title: 'New message',
            body: `${content}`,
            click_action: 'FCM_PLUGIN_ACTIVITY'
        },
        data: {
            page: 'tabs/travel-buddies',
        }
    };`
