### ISSUE TITLE
"Plugin doesn't support this project's cordova version. cordova: 8.1.1"

### ISSUE THREAD

**Issue by SparrowBlaze** [chemerisuk/cordova-plugin-firebase-messaging#102]
When I try to install this plugin, Cordova skips all of my platforms with this error: `Plugin doesn't support this project's cordova version. cordova: 8.1.1, failed version requirement: >=9.0.0`

Is there anything I should try to get this plugin to work with Cordova CLI 9.0?

**Comment by chemerisuk** [comment]
```
npm uninstall -g cordova
npm install -g cordova@9.0.0
```

**Comment by SparrowBlaze** [comment]
No go.  I've reinstalled Cordova twice now, and the same error comes up for all platforms.  I also wonder whether `cordova --version` should report anything other than "`8.1.2 (cordova-lib@8.1.1)`".

**Comment by ketanambekar1** [comment]
Hey, Any solutions? I am getting this issue specially while installing Firebase related plugins..

**Comment by maxymczech** [comment]
@ketanambekar1 I am having same problem, I don't even have `cordova` installed globally, I am using `corber` in a project.

**Comment by DuaneQ** [comment]
Has anyone resolved this issue.  When I check my cordova version is clearly says 9.0.  I'm not sure where it thinks the version is 8.
