### ISSUE TITLE
How to show notification as "PUSH" when app is in foreground(opened) on Android?

### ISSUE THREAD

**Issue by yoldar** [chemerisuk/cordova-plugin-firebase-messaging#103]
I have integrated Firebase Cloud Messaging with my application. When I sent a notification from the Firebase console, if the app is in background or not opened I receive successfully the notification, otherwise if the app is in foreground(opened) I want also receive as "PUSH". This works on iOS but in Android not.

All suggestions are appreciated

**Comment by Lucab95** [comment]
Hi @yoldar, I'm using Cordova-plugin-firebase and to solve this problem I just went on this path:

platforms\android\app\src\main\java\org\apache\cordova\firebase

And modified the following file "FirebasePluginMessagingService.java" 
You will find a TODO in line 122. I set the boolean  showNotification = true; this solved my problem.
I'm now trying Firebase Cloud Messaging plugin and I will let you know if it is the same approach.
I hope it helps.

**Comment by chemerisuk** [comment]
Try to use forceShow option:
cordova.plugins.firebase.messaging.requestPermission({forceShow: true}).then(function() {
    console.log("You'll get foreground notifications when a push message arrives");
});

**Comment by antocorso** [comment]
@chemerisuk I have the same problem as @yoldar and solution you suggested doesn't work!

**Comment by andrebrandaoo** [comment]
@chemerisuk your solution works greate for me.

@antocorso @yoldar i tryed clearing cache and/or reinstalling application.
