### ISSUE TITLE
onBackgroundMessage not fired and app  not opening on notification click

### ISSUE THREAD

**Issue by pilz97** [chemerisuk/cordova-plugin-firebase-messaging#104]
Hi,

I have two problems.
The onBackgroundMessage Event is not triggered, i only receive the onMessage when the App is in foreground while i receive a message.
At first I also didn't get the onMessage but then i added this to my config.xml:
`      <config-file target="AndroidManifest.xml" parent="/manifest/application" >
        <service android:name="by.chemerisuk.cordova.firebase.FirebaseMessagingPluginService">
          <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT"/>
          </intent-filter>
        </service>
      </config-file>`

Is there anything I have to add that i get the onBackgroundMessage to?

The second problem I have is, when i recevie a notification in the background, the push notification appears but when i click on it the app won't come in the foreground :(

Does anyone have a idea what I'm doing wrong?

**Comment by saurabh47** [comment]
Hello @pilz97 ,
I'm also facing same issue.
Do you got the solution for it??

**Comment by deepa1-d** [comment]
Facing the same issue in Android as well as iOS.

**Comment by jcarloss** [comment]
Same issue :(

**Comment by AxiomAim** [comment]
Facing the same issue on Android. Work on iOS

**Comment by theMSY** [comment]
Hello,
I found out that removing the click_action attribute from the notification config array ( i wrote my backend in PHP), resolves the issue. Apparently, the firebase plugin takes charge of creating the appropriate intent and launches the app on its own. No need to add a click_action filter name, because it confuses firebase (?) and leads to canceling the intent all together.

**Comment by jackdaniel9** [comment]
Same issue. «cordova.plugins.firebase.messaging.onBackgroundMessage» not Work on Android.

**Comment by luisVargasGu** [comment]
> Hello,
> I found out that removing the click_action attribute from the notification config array ( i wrote my backend in PHP), resolves the issue. Apparently, the firebase plugin takes charge of creating the appropriate intent and launches the app on its own. No need to add a click_action filter name, because it confuses firebase (?) and leads to canceling the intent all together.

Getting rid of click_action does solve the issue if you don't have a custom data payload, or if the data payload is just title and body.

When I send just title and body, or custom data elements which are empty in a notification payload and the app is in the background. If i click the notification, it opens up the app hitting the .onBackgroundMessage function.

example payload:
{
"notification": {
"title": "test title",
"body": "test body"
},
"data": {
"title": "test title",
"body": "test body",
"link": ""
}
}

However when I send some custom data In my case a url link such as www.example.com, If I click the notification it does not open up the app, and it does not hit the .onBackgroundMessage function.

example payload:
{
"notification": {
"title": "test title",
"body": "test body"
},
"data": {
"title": "test title",
"body": "test body",
"link": "www.example.com"
}
}

If the app is in the foreground any and all payloads hit the .onMessage

**Comment by nimishdesai1989** [comment]
I am facing the same issue. Does anyone have any solution for a workaround ?

**Comment by helloworld123456780** [comment]
Hi, just curious if this issue is already fixed, especially with function onBackgroundMessage not fired?

**Comment by chemerisuk** [comment]
@helloworld123456780 read notes section in https://github.com/chemerisuk/cordova-plugin-firebase-messaging#onbackgroundmessagecallback

**Comment by fcristini** [comment]
Hi, I can't find the notes section of onBackgroundMessage anymore, is removing the click_action the solution for this?

**Comment by dllort** [comment]
The probleM is that on FirebaseMessagingPlugin.sendNotification() there is a check "if (instance != null)" that simply ignores push notifications is the app is not initialize INSTEAD OF INITIALIZE IT. @chemerisuk can this plugin perform this initialization in order to enable push notification when the app is closed?
