### ISSUE TITLE
How to get APNS token from fcm for ios

### ISSUE THREAD

**Issue by akashdeepsharma1991** [chemerisuk/cordova-plugin-firebase-messaging#107]
i am getting the fcm token for ios but i want the apns token for sending the notification. i am using this method mention by you in the doc.

 cordova.plugins.firebase.messaging.getToken("apns-string").then(function (token) {
                console.log("Got device token: from ios ", token);
            });

when i am using this method i am getting token blank. Kindly help in this please.. stuck for a long time

Note: I havnt added [FIRApp configure]; in appdelegate since i am getting error. without it i am able to get the tcm token

**Comment by akashdeepsharma1991** [comment]
@chemerisuk please help

**Comment by chemerisuk** [comment]
Try this code:
```js
firebaseMessaging.requestPermission().then(function() {
  firebaseMessaging.getToken("apns-string").then(apnsToken => {
                        // send apnsToken to server
                    });
});
```

**Comment by akashdeepsharma1991** [comment]
=Hii i tried the above code but not getting the token.. infact the fucntion its self is not getting called

**Comment by akashdeepsharma1991** [comment]
one note i got the token  by using the cordova method and not the ionic methold really a wried behaviour

**Comment by alipetarian** [comment]
You can get token the following way.

      firebase
        .messaging()
        .ios.registerForRemoteNotifications()
        .then(() => {
          console.log('REGISTER FOR REMOTE NOTIFICATIONS');

          firebase
            .messaging()
            .ios.getAPNSToken()
            .then(token => {
              console.log(
                'APNS TOKEN AFTER REGISTRATION FOR BACKGROUND',
                token,
              );
            });
        });
