### ISSUE TITLE
Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

### ISSUE THREAD

**Issue by akashdeepsharma1991** [chemerisuk/cordova-plugin-firebase-messaging#109]
hi i am getting this error while installing your plugin 
Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
using latest version of cordova 9

![Screenshot 2019-08-05 at 1 40 18 PM](https://user-images.githubusercontent.com/33919907/62449009-c7607980-b786-11e9-8241-2e7af52d55cb.png)

**Comment by JPAlfa** [comment]
@akashdeepsharma1991 Do you still have this issue? Could we close this?
