### ISSUE TITLE
Not able to get token in ios with cordova.plugins.firebase.messaging.getToken()

### ISSUE THREAD

**Issue by ShavetaGirdhar** [chemerisuk/cordova-plugin-firebase-messaging#11]
in getToken() method I am always getting null in Promise in case of ios

**Comment by niraj-lal-rahi** [comment]
I am also getting same issue. Any help?

**Comment by dangdhh** [comment]
The same problem.

**Comment by charlesRms** [comment]
Samedi problem

**Comment by thandaanda** [comment]
@fredmanders Yup, this is the same issue. I am also trying to figure out the solution. I have little to zero experience with Swift/Objective C.

**Comment by chemerisuk** [comment]
To everyone in this thread - go to `Firebase project settings > Cloud messaging > iOS app configuration` and make sure you uploaded valid APNs Authentication Key.

https://firebase.google.com/docs/cloud-messaging/ios/certs

**Comment by thandaanda** [comment]
Hi @chemerisuk, thanks for quick reply. I have set valid authentication key in Firebase console and I am getting token if I use cordova-plugin-firebase. However, that plugin does not play well with dynamic links plugin.

**Comment by chemerisuk** [comment]
@thandaanda what code do you use to get the token? What other cordova plugins do you have?

**Comment by fredmanders** [comment]
Hi @chemerisuk, I've tried both the APNs Authentication Key and the APNs Certificates in the Firebase settings. But I still don't get a token. Same as @thandaanda I do get a token with the firebase plugin, but then I lose Dynamic Links, which I need for passwordless login (and other things). In this Stackoverflow question I posted, you can see which platform and plugins I use: https://stackoverflow.com/questions/51657315/cordova-ionic-project-with-firebase-messaging-and-firebase-dynamic-links

**Comment by fredmanders** [comment]
@chemerisuk Adding cordova-plugin-firebase-analytics was the fix for me!!! Wow! I was breaking my head over this for about a week now. Thanks you so much!

I register for push after sign up, which triggers this code (I use the Ionic Native plugins):

public async registerPushNotification(currentUser) {
    let token = await this.getToken();
    return this.saveTokenToFirestore(currentUser.uid, token);
}

private async getToken() {
    let token;
    if (this.platform.is('android')) {
      token = await this.firebaseMessaging.getToken();
    } 
    if (this.platform.is('ios')) {
      token = await this.firebaseMessaging.getToken();
      const perm = await this.firebaseMessaging.requestPermission();
    }
    return token;
}

**Comment by chemerisuk** [comment]
I'm guessing the source of problem is that without the analytics plugin firebase is not initialized. As a result some methods do not work properly.

**Comment by chemerisuk** [comment]
@fredmanders

**Comment by fredmanders** [comment]
@chemerisuk Yes, now it seems to work for iOS as well WITHOUT the analytics plugin. Even better!!

**Comment by chemerisuk** [comment]
Thank you, the fix was published in v1.1.1
