### ISSUE TITLE
Library not found for -lFirebaseCore in xocde

### ISSUE THREAD

**Issue by yashdabi** [chemerisuk/cordova-plugin-firebase-messaging#112]
https://ionicframework.com/docs/native/firebase-messaging/
This plugin is working fine for android but when i am building ionic 4 project in xocde it's showing these errors

> ld: warning: directory not found for option '-L/Users/syedaqdaszaidi/Library/Developer/Xcode/DerivedData/ShiaFM-cmchzodxxqifygckxxojpqogtqnp/Build/Products/Debug-iphonesimulator/FirebaseCore'
ld: warning: directory not found for option '-L/Users/syedaqdaszaidi/Library/Developer/Xcode/DerivedData/ShiaFM-cmchzodxxqifygckxxojpqogtqnp/Build/Products/Debug-iphonesimulator/FirebaseInstanceID'
ld: warning: directory not found for option '-L/Users/syedaqdaszaidi/Library/Developer/Xcode/DerivedData/ShiaFM-cmchzodxxqifygckxxojpqogtqnp/Build/Products/Debug-iphonesimulator/FirebaseMessaging'
ld: warning: directory not found for option '-L/Users/syedaqdaszaidi/Library/Developer/Xcode/DerivedData/ShiaFM-cmchzodxxqifygckxxojpqogtqnp/Build/Products/Debug-iphonesimulator/GoogleUtilities'
ld: warning: directory not found for option '-L/Users/syedaqdaszaidi/Library/Developer/Xcode/DerivedData/ShiaFM-cmchzodxxqifygckxxojpqogtqnp/Build/Products/Debug-iphonesimulator/Protobuf'
ld: warning: directory not found for option '-L/Users/syedaqdaszaidi/Library/Developer/Xcode/DerivedData/ShiaFM-cmchzodxxqifygckxxojpqogtqnp/Build/Products/Debug-iphonesimulator/nanopb'
ld: library not found for -lFirebaseCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**What I have already done**
downgrade Cordova form 9 to 8 version - not working
install pod and update in platform/ios - not working
open workspace file instead of xcodeproj - not working (showing another error - could not find a valid GoogleService-Info.plist in your project. )

https://ionicframework.com/docs/native/fcm
FCM plugin is working fine for ios but in android, it's making version conflict with firebase dynamic link, that's why I used cordova-plugin-firebase-messaging this plugin 

I have been searching since last 3 days, please help

**Comment by leandroide** [comment]
Hi,
I solved this problem:

I added my GoogleService-Info.plist file to the "Resources" directory manually on Xcode:

Print:

<img width="332" alt="Screen Shot 2019-09-05 at 17 30 16" src="https://user-images.githubusercontent.com/8044863/64378345-e1e67680-d002-11e9-9c2e-383b2e7b7573.png">

**Comment by yashdabi** [comment]
@leandroide thanks it's working
I follow these steps 

`ionic cordova plugin remove cordova-plugin-firebase-messaging`
`ionic cordova platform remove ios`

paste GoogleService-Info.plist file to root project directory

`<platform name="ios">
<resource-file src="GoogleService-Info.plist" />
 </platform>
`

above line will automatically add GoogleService-Info.plist to Resources folder, no need to do manually

`ionic cordova plugin add cordova-plugin-firebase-messaging`
`ionic cordova platform add ios`
`ionic cordova build ios`

project->platform->ios->
open xcworkspace file instead of xcodeproj 
we need to open xcworkspace because of POD installed some libraries in our project.

**Comment by andrei-ce** [comment]
For me this was just a matter of removing the debug config from the General settings. Go figure why.
![Screen Shot 2021-05-28 at 15 01 02](https://user-images.githubusercontent.com/55623219/119987722-a0abac80-bfc5-11eb-9308-ac54fc622970.jpg)
