### ISSUE TITLE
Push Notification Popup not working on >= Android O . When app is in app background. 

### ISSUE THREAD

**Issue by nuvolo-Ankit** [chemerisuk/cordova-plugin-firebase-messaging#118]
App is showing silent notification when we're sending notification from API. We tried your force method as well, but not working. Any solution?

I have also created and made some changes in your code to enable Popup notification .
URL : https://github.com/xDAnkit/cordova-plugin-firebase-messaging/commit/a163f9957d2d634e34261f9db0077b08e340cfb4

You can review and let me know your thoughts about it.

**Comment by nuvolo-Ankit** [comment]
Hello @chemerisuk  . Any update on this?

**Comment by LuffMi** [comment]
Any updates on this? I am also only receiving silent notifications. When the App is in the background, the app receives the notification in the status bar, but there isn't a popup that appears, and when the App is in the foreground, I get a popup, but the notification does not stay in the status bar.

**Comment by akadebnath** [comment]
@chemerisuk The peak-in/pop-up notification is a basic requirement for push notifications. Can you please review what @nuvolo-Ankit has done and merge it if it meets the requirement.
Thank you for the great plugin.

**Comment by chemerisuk** [comment]
Should be fixed in 4.3.0
