### ISSUE TITLE
Migration GCM to FCM

### ISSUE THREAD

**Issue by humbertomonterrosa** [chemerisuk/cordova-plugin-firebase-messaging#12]
Hi @chemerisuk 
Google announces that GCM will become deprecated in 2019, does this project already use FCM?

![screenshot](https://user-images.githubusercontent.com/1129417/39770123-c5fbde60-52b3-11e8-9616-be4b7559d1e6.png)

**Comment by chemerisuk** [comment]
Yes, it does
