### ISSUE TITLE
how to trigger function when receive FCM in background without tapping in cordova

### ISSUE THREAD

**Issue by ngoctuan001** [chemerisuk/cordova-plugin-firebase-messaging#121]
im developing a cordova app with firebase cloud messaging. 

The requirement is i need to have the voice notification (phone to read the text out loud when receiving notification). im doing this by using

`cordova-plugin-texttospeech`
However, I can only do this when the app is in foreground using onMessage function : `cordova.plugins.firebase.messaging.onMessage(callback); `<= i put the TTS function in the callback

However, when the app is in background, this not works: `cordova.plugins.firebase.messaging.onBackgroundMessage(callback); `<= put the TTS function not works, because the callback only triggered when user tapped the notification. I want it triggered as soon as they receive it

Anybody has any idea how to do this ?

**Comment by chemerisuk** [comment]
Not related to the plugin. Ask questions on a forum.
