### ISSUE TITLE
library not found for -lFirebaseCore Xcode 

### ISSUE THREAD

**Issue by MhmdKorhani** [chemerisuk/cordova-plugin-firebase-messaging#122]
Xcode Version: 11.1
Cordova: 9.0.0

PodFile:
platform :ios, '9.0'
target 'MyPets' do
	project 'MyPets.xcodeproj'
	pod 'Firebase/Core', '~> 6.3.0'
	pod 'Firebase/Messaging', '~> 6.3.0'
end

GoogleService-Info.plist is inside the app folder.

build error: library not found for -lFirebaseCore

**Comment by JPAlfa** [comment]
I have the same issue with XCode 10.2.1, with cordova-ios 5.0.1 and cordova 9. I'm using the plugin on the last version (4.0.1).
This is the output on Xcode:

ld: warning: directory not found for option '-L/Users/replyit/Library/Developer/Xcode/DerivedData/{{AppName}}-eothmnxcqctucyeaqidicsfwagln/Build/Products/Debug-iphoneos/FirebaseCore'
ld: warning: directory not found for option '-L/Users/replyit/Library/Developer/Xcode/DerivedData/{{AppName}}-eothmnxcqctucyeaqidicsfwagln/Build/Products/Debug-iphoneos/FirebaseInstanceID'
ld: warning: directory not found for option '-L/Users/replyit/Library/Developer/Xcode/DerivedData/{{AppName}}-eothmnxcqctucyeaqidicsfwagln/Build/Products/Debug-iphoneos/FirebaseMessaging'
ld: warning: directory not found for option '-L/Users/replyit/Library/Developer/Xcode/DerivedData/{{AppName}}-eothmnxcqctucyeaqidicsfwagln/Build/Products/Debug-iphoneos/GoogleUtilities'
ld: warning: directory not found for option '-L/Users/replyit/Library/Developer/Xcode/DerivedData/{{AppName}}-eothmnxcqctucyeaqidicsfwagln/Build/Products/Debug-iphoneos/Protobuf'
ld: warning: directory not found for option '-L/Users/replyit/Library/Developer/Xcode/DerivedData/{{AppName}}-eothmnxcqctucyeaqidicsfwagln/Build/Products/Debug-iphoneos/nanopb'
ld: library not found for -lFirebaseCore

Some warnings and this error. Anyone has a solution?

**Comment by JPAlfa** [comment]
@chemerisuk Can you help us? Thanks in advance

**Comment by JPAlfa** [comment]
I fixed my error by putting this tag on config.xml

`<platform name="ios">`
`<resource-file src="GoogleService-Info.plist" />`
`<platform name="ios">`
