### ISSUE TITLE
App crashes after first launch with cordova-plugin-firebase-messaging

### ISSUE THREAD

**Issue by JPAlfa** [chemerisuk/cordova-plugin-firebase-messaging#123]
- [x] Cordova 9
- [x] Cordova-Android 8.1.0 
- [x] Plugin is on 4.0.0 version

After installing this plugin my android app crashes, but just on the first launch. When I open it again works fine.
I get this error in android crash:

> E/AndroidRuntime( 5494): FATAL EXCEPTION: main
>  E/AndroidRuntime( 5494): Process: br.com.omint.apps.minhaomint, PID: 5494
>  E/AndroidRuntime( 5494): java.lang.RuntimeException: Unable to create service by.chemerisuk.cordova.firebase.FirebaseMessagingPluginService: java.lang.NullPointerException
>  E/AndroidRuntime( 5494):     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
>  E/AndroidRuntime( 5494):     at android.app.ActivityThread.access$1300(ActivityThread.java:199)
>  E/AndroidRuntime( 5494):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
>  E/AndroidRuntime( 5494):     at android.os.Handler.dispatchMessage(Handler.java:106)
>  E/AndroidRuntime( 5494):     at android.os.Looper.loop(Looper.java:193)
>  E/AndroidRuntime( 5494):     at android.app.ActivityThread.main(ActivityThread.java:6669)
>  E/AndroidRuntime( 5494):     at java.lang.reflect.Method.invoke(Native Method)
>  E/AndroidRuntime( 5494):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>  E/AndroidRuntime( 5494):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
>  E/AndroidRuntime( 5494): Caused by: java.lang.NullPointerException
>  E/AndroidRuntime( 5494):     at android.os.Parcel.createException(Parcel.java:1948)
>  E/AndroidRuntime( 5494):     at android.os.Parcel.readException(Parcel.java:1910)
>  E/AndroidRuntime( 5494):     at android.os.Parcel.readException(Parcel.java:1860)
>  E/AndroidRuntime( 5494):     at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:1751)
>  E/AndroidRuntime( 5494):     at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:541)
>  E/AndroidRuntime( 5494):     at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:529)
>  E/AndroidRuntime( 5494):     at by.chemerisuk.cordova.firebase.FirebaseMessagingPluginService.onCreate(FirebaseMessagingPluginService.java:59)
>  E/AndroidRuntime( 5494):     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3532)
>  E/AndroidRuntime( 5494):     ... 8 more
>  E/AndroidRuntime( 5494): Caused by: android.os.RemoteException: Remote stack trace:
>  E/AndroidRuntime( 5494):     at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:111)
>  E/AndroidRuntime( 5494):     at com.android.server.notification.RankingHelper.createNotificationChannel(RankingHelper.java:606)
>  E/AndroidRuntime( 5494):     at com.android.server.notification.NotificationManagerService$10.createNotificationChannelsImpl(NotificationManagerService.java:2227)
>  E/AndroidRuntime( 5494):     at com.android.server.notification.NotificationManagerService$10.createNotificationChannels(NotificationManagerService.java:2242)
>  E/AndroidRuntime( 5494):     at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:256)

Am I missing something or this is a plugin problem?

**Comment by jamesfdickinson** [comment]
I had a similar issue, NullPointerException, in the FirebaseMessagingPluginService.onCreate().  I see you have those in your stack trace.  
This line was an unexpected null at: this.defaultNotificationColor = ContextCompat.getColor(this, ai.metaData.getInt(NOTIFICATION_COLOR_KEY)); in FirebaseMessagingPluginService.onCreate(). ai.metaData.getInt(NOTIFICATION_COLOR_KEY)) was null because it was looking for NOTIFICATION_COLOR_KEY in the AndroidManifest.xml

To solve it I added this to the config.xml

        <config-file parent="/manifest/application" target="AndroidManifest.xml">
           <meta-data  android:name="com.google.firebase.messaging.default_notification_color" android:value="#FF00FF"/>
        </config-file>

Hope that helps

**Comment by chemerisuk** [comment]
Bugfix published in v4.0.1, thanks for the report.

**Comment by jamesfdickinson** [comment]
Thanks
