### ISSUE TITLE
Conflict with another plugin?

### ISSUE THREAD

**Issue by htorbov** [chemerisuk/cordova-plugin-firebase-messaging#124]
I get:

> cordova-plugin-firebase-messaging depends on Firebase/Analytics, which may conflict with another plugin. Firebase/Analytics@~> 6.3.0 is already installed and was not overwritten.

---

When I'm installing:
```
cordova plugin add cordova-plugin-wkwebview-engine
cordova plugin add cordova-support-google-services
cordova plugin add cordova-plugin-firebase-analytics
cordova plugin add cordova-plugin-firebase-authentication
cordova plugin add cordova-plugin-firebase-messaging
cordova plugin add cordova-plugin-nativestorage
cordova plugin add cordova-plugin-statusbar
cordova plugin add cordova-plugin-splashscreen
cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-camera
cordova plugin add cordova-plugin-dialogs
```

---

Do I need to bypass the `cordova-plugin-firebase-analytics` and if I do, will I still have the Analytics?

---

Thank you!

**Comment by chemerisuk** [comment]
I think it’s just a warning that should not break anything.

**Comment by htorbov** [comment]
@chemerisuk, thank you for these wonderful plugins, they're working perfectly! :-)
