### ISSUE TITLE
Program type already present: android.support.v4.app.INotificationSideChannel

### ISSUE THREAD

**Issue by dpatel** [chemerisuk/cordova-plugin-firebase-messaging#126]
After integrating this library getting an error 

`Program type already present: android.support.v4.app.INotificationSideChannel`

**Comment by antwal** [comment]
same problem, i have try:

```
cordova plugin add cordova-plugin-androidx --save
cordova plugin add cordova-plugin-androidx-adapter --save
```

build is ok, but notification not working.
