### ISSUE TITLE
Not receiving data messages on Android

### ISSUE THREAD

**Issue by gvolpe1968** [chemerisuk/cordova-plugin-firebase-messaging#129]
I'm sending two types of firebase messages : 
- notifications and custom messages.
but I'm seeing that the only showing on Android are notifications.
Custom data messages are not showing.
Do I have to set some special fields on the data_payload to make them shown ? 
moreover I read about the need to create a  notification channel... How can I create a channel using cordova? I know how to using native Java app, but we are in the cordova world.

**Comment by chemerisuk** [comment]
@gvolpe1968 this is correct behavior. For data messages register `onMessage`/`onBackgroundMessage` callbacks and trigger some UI.

**Comment by chemerisuk** [comment]
At present plugin does not have any methods for notification channel CRUD. This is in TODO list

**Comment by chemerisuk** [comment]
Notification channel CRUD release in v4.2.1
