### ISSUE TITLE
How to handle notification tapped in android

### ISSUE THREAD

**Issue by niraj-lal-rahi** [chemerisuk/cordova-plugin-firebase-messaging#13]
@chemerisuk  I want to handle push notification tapped to open that notification.

**Comment by chemerisuk** [comment]
Register https://github.com/chemerisuk/cordova-plugin-firebase-messaging#onbackgroundmessagecallback handler

**Comment by niraj-lal-rahi** [comment]
@chemerisuk  I have used that method. I want to open notification like this when I will tapp on notification in notification bar
FCMPlugin.onNotification(function(data){
    if(data.wasTapped){
      //Notification was received on device tray and tapped by the user.
      alert( JSON.stringify(data) );
    }else{
      //Notification was received in foreground. Maybe the user needs to be notified.
      alert( JSON.stringify(data) );
    }
});
