### ISSUE TITLE
Messages are not showing in iOS 

### ISSUE THREAD

**Issue by gvolpe1968** [chemerisuk/cordova-plugin-firebase-messaging#130]
I'm sending two types of firebase messages : 
- notifications and custom messages.
but I'm seeing that they are both not showing.
Do I have to set some special fields on the data_payload or notification_payload to make them shown in iOS?

**Comment by adrigardi90** [comment]
I'm testing the plugin and also having the same issue: no problems on Android but I'm not getting any notifications on iOS (once all has been configured in the cordova project and Firebase)

**Comment by chemerisuk** [comment]
@gvolpe1968 @adrigardi90 do you have issues in showing foreground or background notifications? Data-only messages do not display anything.

**Comment by gvolpe1968** [comment]
@chemerisuk hi  Maksim, I'm not able to see neither foreground nor background .
> Data-only messages do not display anything 
that means the payload should always have the notification stream and that is what is always shown ?
thx

**Comment by dogofpavlov** [comment]
I'm also having the same issue. Messages show up on Android and not iOS.

**Comment by seba316d** [comment]
Any solutions ?

**Comment by dogofpavlov** [comment]
I went to phonegap push plugin, working both platforms

**Comment by chemerisuk** [comment]
Possible duplicate of https://github.com/chemerisuk/cordova-plugin-firebase-messaging/issues/95
