### ISSUE TITLE
Ability to get the Firebase instance id

### ISSUE THREAD

**Issue by sagrawal31** [chemerisuk/cordova-plugin-firebase-messaging#131]
How can we get the Firebase instance id?

The fork of Dave has this feature https://github.com/dpa99c/cordova-plugin-firebasex/tree/9.0.1#getid

**Comment by chemerisuk** [comment]
@sagrawal31 is it different from https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#public-taskstring-getappinstanceid-?

**Comment by sagrawal31** [comment]
I think it's the same thing.

**Comment by chemerisuk** [comment]
@sagrawal31 just pushed 31c32650a68efd770a4d694b3c41c8ee3db9c856. Do you mind to test?

**Comment by sagrawal31** [comment]
I'll test this out.

**Comment by sagrawal31** [comment]
@chemerisuk tested on iOS. Working fine. I hope this will work in Android, too. 

Do you want me to test on Android before you release the version?

**Comment by chemerisuk** [comment]
@sagrawal31 Android should be fine. Published in v4.1.1

**Comment by sagrawal31** [comment]
Thank you for quick release of the feature, @chemerisuk 

I appreciate 👏
