### ISSUE TITLE
Possible inconsistency in the behaviour of onTokenRefresh callback

### ISSUE THREAD

**Issue by sagrawal31** [chemerisuk/cordova-plugin-firebase-messaging#138]
## Description

Using the latest version of this plugin i.e. `4.4.0` along with other your plugins (thanks for maintaining these 🙏):

```json
"cordova-plugin-firebase-analytics": "4.3.0",
"cordova-plugin-firebase-crash": "2.2.0",
"cordova-plugin-firebase-dynamiclinks": "4.4.0",
"cordova-plugin-firebase-messaging": "4.4.0",
```

I have registered the following callbacks:

```javascript
cordova.plugins.firebase.messaging.getToken().then(function(token) {
    saveTokenInServer(token);
});

cordova.plugins.firebase.messaging. onTokenRefresh().then(function(token) {
    saveTokenInServer(token);
});
```

## Actual Behaviour

On the first app launch (tested with Android), both the callbacks are called. But on the subsequent app launches, only `getToken` is called (which is obvious), but `onTokenRefresh` is not called (the token is the same).

This results in the two server call simultaneously (although I have added a workaround for this in my code).

## Expected Behaviour

As per my understanding from the Firebase native docs, either of the following should happen:

1. `onTokenRefresh` should be called every time on app launch irrespective it is a first-time app launch or not. Or,
2. `onTokenRefresh` should not be called on the first app launch (of course, will be called when the token changes).

**Please note:** I'm raising this as a possible scenario of inconsistency. So though of raising this issue. Because even as per your description **Triggers every time when FCM token updated. You should usually call getToken to get an updated token and send it to server.**, one can't call `getToken()` from inside `onTokenRefresh()` because it is getting called on the first app launch.

## Environment

- cordova-lib@9.0.1 with:
  - cordova-common@3.2.0
  - cordova-create@2.0.0
  - cordova-fetch@2.0.1
  - cordova-serve@3.0.0

- Environment: 
  - OS: darwin
  - Node: v10.16.0
  - npm: 6.9.0

**Comment by chemerisuk** [comment]
> on the subsequent app launches, only getToken is called (which is obvious), but onTokenRefresh is not called (the token is the same)

@sagrawal31 this is correct behavior. `onTokenRefresh` is called only when app instanceId was changed.

**Comment by sagrawal31** [comment]
Thanks for the reply @chemerisuk
