### ISSUE TITLE
onMessage() and onBackgroundMessage() not triggering in iOS

### ISSUE THREAD

**Issue by xae217** [chemerisuk/cordova-plugin-firebase-messaging#139]
Similar to #95 but using content_available: 1 as suggested is not working for me. Methods work properly in iOS.
I am receiving notifications from firebase but when the app is in the foreground, onMessage() is not firing. When the app is in the background, I receive the notification but when I click on it onBackgroundMessage() is not triggered.

**Here is the weird part**: onBackgroundMessage() _is_ triggered when the app is _not running_. When I receive a notification, I can tap on it and the correct routing will happen

The payload I am using looks like this:
``{ "default": "title: \"Test default\" - body: \"Test Body\"", "GCM": "{ \"notification\": { \"title\": \"Test GCM\", \"body\": \"test\" }, \"data\": { \"url\": \"business\", \"businessId\": \"5\", \"notId\": 197 }, \"content_available\": 1 }", "APNS": "{ \"aps\": { \"alert\": { \"title\": \"Test APS\", \"body\": \"test\", \"url\": \"business\", \"businessId\": \"5\" }, \"content_available\": 1 } }"}``
I have tried placing content_available everywhere in the payload. I tried using content-available and contentAvailable: true as well.
I am using the ionic native wrapper and use ngZone.run() to handle the data from the Observer like this: 
```
this.firebaseMessaging.onBackgroundMessage().subscribe((data) => {
      this.ngZone.run(() => this.handleIncomingNotificationRouting(data));
    }, (err) => {
      console.log(`FirebaseMessaging => ERROR Received a background notification => ${JSON.stringify(err)}`);
    });
```
I have tried calling the plugin directly and using the ngZone.run in a similar way but onBackgroundMessage() is not triggered.

I have not been able to get onMessage() working at all on iOS.

Some more info: 
cordova v8.1.2
cordova-plugin-firebase-messaging v1.4.0 (having unrelated issues with cordova v9 so cannot update plugin to latest)
cordova-ios v5.0.0
ionic v5.1.0
Using AWS SNS in between the back-end spring server and FCM.
Testing on an iOS 12 device.

Any help would be appreciated. Thanks!

**Comment by FilippoPagano** [comment]
`cordova plugin add cordova-plugin-firebase-messaging@4.1.1` is all you need

**Comment by chemerisuk** [comment]
@xae217 please try to use the latest version. I do not have time tom maintain old versions.

**Comment by xae217** [comment]
I was still running into the same issue after upgrading to the latest version. However, I was able to solve my issue so in case anyone using AWS SNS and FCM runs into the same issue, here is what solved it for me: 
Looking at the FCM docs, FCM allows us to use content_available: true as an option parameter like this (note that this is the legacy format):
```
{
 "to" : "<token",
 "collapse_key" : "type_a",
 "content_available": true
 "notification" : {
     "body" : "Body of Your Notification",
     "title": "Title of Your Notification"
 },
 "data" : {
     "data-key": "data value"
 }
}
```
However, AWS does not allow us to send parameters outside the notification or data payloads. If I place the tag there it will be ignored. After some testing it seems like FCM also allows the content_available: true flag to be placed inside the notification payload like this:
```
{
 "to" : "<token>",
 "collapse_key" : "type_a"
 "notification" : {
     "body" : "Body of Your Notification",
     "title": "Title of Your Notification",
     "content_available": true,
 },
 "data" : {
     "data-key": "data value"
 }
}
```
I was also able to do this through AWS and it worked correctly. 
I do want to note that using content_available: 1 did not work for me. It only works when using content_available: true.
