### ISSUE TITLE
cordova.plugins.firebase.messaging.onBackgroundMessage not working in my app. nothing is shown.

### ISSUE THREAD

**Issue by DenisMrGnusa** [chemerisuk/cordova-plugin-firebase-messaging#14]
this my script
cordova.plugins.firebase.messaging.onBackgroundMessage(function(payload) {
       console.log("New background FCM message: ", payload);
 });

thank you

**Comment by chemerisuk** [comment]
Published 0.14.0

**Comment by DenisMrGnusa** [comment]
thanks for your fast response, I have tried what you have described.. but the code still not working.
 my same code : 

cordova.plugins.firebase.messaging.onBackgroundMessage(function(payload) {
	console.log(payload);
});

what's wrong with my code..?

**Comment by DenisMrGnusa** [comment]
thank you for your fast response, I have tried what you have described..
but the code still not working.
 my same code :

cordova.plugins.firebase.messaging.onBackgroundMessage(function(payload) {
console.log(payload);
});

what's wrong with my code..?

On Wed, May 30, 2018 at 2:44 AM, Maksim Chemerisuk <notifications@github.com
