### ISSUE TITLE
does the plugin depends on "cordova-plugin-firebase-analytics"

### ISSUE THREAD

**Issue by EmreAkkoc** [chemerisuk/cordova-plugin-firebase-messaging#147]
I am coming from "cordova-plugin-firebasex" I no longer want to use it because I use some other methods for firebase analytics and I only need the firebase messaging functionality. so when I was installing this plugin I realized that it also installs "cordova-plugin-firebase-analytics" along with (expectedly) "cordova-support-android-plugin". so does firebase messaging depend on firebase analytics ? I am no way a pro on the subject but I just don't want to install an additional plugin if I wont use it.

**Comment by chemerisuk** [comment]
@EmreAkkoc correct, it has dependency on analytics. Read tables below
https://firebase.google.com/docs/android/setup#available-libraries
https://firebase.google.com/docs/ios/setup#available-pods
