### ISSUE TITLE
track opened notification

### ISSUE THREAD

**Issue by Alkashi** [chemerisuk/cordova-plugin-firebase-messaging#152]
Hi,

The plugin works great on both android and iOS, the notifications are received without any issue. (GOOD JOB !)
On the Firebase dashboard, i am able to send message BUT impossible to track when the message is opened.

[ This was possible with the firebasex plugin on android (not working with iOS so i decided to use this one (chemerisuk/cordova-plugin-firebase-messaging) ]

Do you know how to perform that ? ( = when a push is opened, I saw it on the FCM dashboard)

Many thanks !

**Comment by chemerisuk** [comment]
Use https://github.com/chemerisuk/cordova-plugin-firebase-messaging#onbackgroundmessagecallback

**Comment by Alkashi** [comment]
@chemerisuk you mean I have to do it myself ? Perform a call to a webservice not included on the plugin ?

**Comment by chemerisuk** [comment]
@Alkashi I don't understand your question. `notification_open` is tracked automatically.

https://support.google.com/firebase/answer/6317485?hl=en
