### ISSUE TITLE
Build failed on ios ionic 3 

### ISSUE THREAD

**Issue by posdevelopers** [chemerisuk/cordova-plugin-firebase-messaging#154]
I am having the following error when i am trying to build .

** BUILD FAILED **

The following build commands failed:
        CompileC /var/root/Library/Developer/Xcode/DerivedData/Quick_Z_Laundry-gfzmljacvkqqjjbcgohzrydhchgv/Build/Intermediates.noindex/Quick\ Z\ Laundry.build/Debug-iphonesimulator/Quick\ Z\ Laundry.build/Objects-normal/x86_64/FirebaseAnalyticsPlugin.o /Users/a2zmac/Desktop/latest/quickz/platforms/ios/Quick\ Z\ Laundry/Plugins/cordova-plugin-firebase-analytics/FirebaseAnalyticsPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by chemerisuk** [comment]
This is a cordova plugin. Ask ionic team instead.
