### ISSUE TITLE
cordova-support-google-services deprecated with cordova-android 9

### ISSUE THREAD

**Issue by fbrun** [chemerisuk/cordova-plugin-firebase-messaging#156]
Hello,
cordova-support-google-services is marked as dependency in plugin.xml, but with cordova-android 9, this plugin is deprecated and no more compatible.

Do we have to downgrade to an older version of cordova-android ?

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-support-google-services/commit/5fd94d9459983409d1bd2c9eca10ec80272b1305

**Comment by fbrun** [comment]
Thanks for that

Do you plan to remove dependency tag in cordova-plugin-firebase-messaging/plugins.xml ?

**Comment by chemerisuk** [comment]
@fbrun no plans to remove the dependency for now, because many developers still use `cordova-android` below version 9.

**Comment by fbrun** [comment]
Ok thanks for you return
