### ISSUE TITLE
Error on install 

### ISSUE THREAD

**Issue by danielmosho** [chemerisuk/cordova-plugin-firebase-messaging#164]
Installing "cordova-plugin-firebase-messaging" for android
Installing "cordova-plugin-firebase-analytics" for android
Installing "cordova-support-android-plugin" for android
Failed to install 'cordova-plugin-firebase-analytics': CordovaError: Version of installed plugin: "cordova-support-google-services@1.1.0" does not satisfy dependency plugin requirement "cordova-support-google-services@^1.3.2". Try --force to use installed plugin as dependency.
   
Failed to install 'cordova-plugin-firebase-messaging': CordovaError: Version of installed plugin: "cordova-support-google-services@1.1.0" does not satisfy dependency plugin requirement "cordova-support-google-services@^1.3.2". Try --force to use installed plugin as dependency.
   
Version of installed plugin: "cordova-support-google-services@1.1.0" does not satisfy dependency plugin requirement "cordova-support-google-services@^1.3.2". Try --force to use installed plugin as dependency.

**Comment by chemerisuk** [comment]
cordova plugin rm cordova-support-google-services --force
cordova plugin add cordova-support-google-services@latest

**Comment by danielmosho** [comment]
@chemerisuk Thank you, now I have this

Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0, failed version requirement: <9.0.0
Skipping 'cordova-support-google-services' for android

There is a dependency whit cordova-plugin-firebase-analytics, can I use this pluggin whitout analytics?

**Comment by chemerisuk** [comment]
> Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0, failed version requirement: <9.0.0
This is OK, because `cordova-android@9` supports new gradle plugin preferences.

> There is a dependency whit cordova-plugin-firebase-analytics, can I use this plugin whitout analytics?
In theory yes, but you need analytics to catch messaging events on the dashboard.
