### ISSUE TITLE
Creating a local notification using the data received in onBackgroundMessage() works only on receiving the first Background notification

### ISSUE THREAD

**Issue by 36Anjali** [chemerisuk/cordova-plugin-firebase-messaging#165]
I am creating local notification using the data message received in onBackgroundMessage() callback when app is in background.
I am receiving the callback in both android and iOS.

In iOS I am able to create local notification on receiving the first background notification but when I send a notification again in background its getting in to the callback but the function inside it executes only if I open the app once and minimise it again.

In Android its working as expected. I am using Firebase HTTP/v1 API to push the notifications.

Notification Payload : 
{
 "message" : {
  "token" : "device token"
 "data" : {
   "notification_debtor" : "xxxx",
   "notification_id" : "xx",
   "notification_category" : "xxx",
   "notification_type" : "xxxx",
   "notification_heading" : "xxxx",
   "notification_content_1" : "xxxx"
   "notification_content_2" : "xxxx"
   "notification_date_time" : "2020-09-21T06:50:23Z",
   "content-available" : 1,
   "force-start" : 1
   }
  }
}

ionic 5.4.16
cordova-plugin-firebase-messaging: 4.6.1
@ionic-native/firebase-messaging: ^5.28.0
@ionic-native/local-notifications: ^5.28.0
cordova-plugin-local-notification: 0.9.0-beta.3
cordova-ios: 6.1.1
cordova-android: 8.1.0

Kindly help!!!

**Comment by chemerisuk** [comment]
@36Anjali iOS can pause your background app process so JS might not work reliably.
