### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Ruudje87** [chemerisuk/cordova-plugin-firebase-messaging#166]
I want to add the plugin cordova-plugin-firebase-messaging but when i want to build i receive an error.

> Task :app:compileReleaseJavaWithJavac FAILED
/myapp/platforms/android/app/src/main/java/nl/xservices/plugins/FileProvider.java:4: error: package android.support.v4.content does not exist
public class FileProvider extends android.support.v4.content.FileProvider {

> FAILURE: Build failed with an exception.

> What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

this only occurs when i add this plugin. ive added it via the config.xml
```xml
<plugin name="cordova-plugin-firebase-messaging" spec="4.6.1" />
```

Cordova version 10.0.0
Android platform add 8.0.0

**Comment by chemerisuk** [comment]
Android X related problem, try googling.
