### ISSUE TITLE
Unable to receive Data message on ios device.

### ISSUE THREAD

**Issue by farazahmadvaival** [chemerisuk/cordova-plugin-firebase-messaging#168]
I am receiving notification in the background and foreground for both ios and android devices. but i am unable to receive data message in ios device. Data messages are working for android but not for ios. My code is written below:

  this.firebaseMessaging.onMessage().subscribe(data => {
                console.log('message data: ', JSON.stringify(data));
                this.handleNotifications(data);
            });
            this.firebaseMessaging.onBackgroundMessage().subscribe(data => {
                console.log('onBackgroundMessage data: ', JSON.stringify(data));
                this.handleNotifications(data);
            });

both subscriptions did not receiving any data message for ios.

**Comment by 123dma** [comment]
I also can't get the notification data on Android. 
What's your code for Android?

My code
```
 cordova.plugins.firebase.messaging.onBackgroundMessage(function (payload) {
                alert("New background FCM message onBackgroundMessage: ", payload);
 });
```

My Request

```
String data = '{"notification": {"body": " [MY DATA]","title": "[MY DATA]"}, "priority": "high", "data": { "title": "O Flutter" ,"click_action": "NOTIFICATION_CLICK", "id":"1",  "status": "done"}, "to": "[MY TOKEN]"}';

http.post("https://fcm.googleapis.com/fcm/send",
                      body: data,
                      headers: {
                        "Content-Type": "application/json",
                        "Authorization":
                            "key=[MY TOKEN]"
});
```

When I click on the notification it opens the App. But the payload returns empty, I would like to get the data.
Could someone help?

**Comment by maxymczech** [comment]
(almost) same issue here, for me on Android device, payload in onBackgroundMessage returns object like this:

```
{
  collapse_key: "com.xxx",
  from: "...",
  google.delivered_priority: "high",
  google.message_id: "0:...",
  google.original_priority: "high",
  google.sent_time: 1603748296067,
  google.ttl: 1234567
}
```

But none of the payload data I actually need to use is not included.

**Comment by DuaneQ** [comment]
I'm able to get data on Android but not iOS.
Is this still an outstanding issue?

`  foregroundMessage() {
    this.fbm.onMessage()
    .subscribe(async data => {
      console.log('foreground msg',  JSON.stringify(data));
      const toast = await this.toastCtrl.create({
        message: `${data.gcm.body} - ${data.gcm.title}`,
        duration: 3000
      });
      toast.present();
    });
  }`

    "cordova-android": "^8.1.0",
    "cordova-android-support-gradle-release": "^3.0.1",
    "cordova-ios": "^6.1.1",
    "cordova-plugin-androidx": "^3.0.0",
    "cordova-plugin-androidx-adapter": "^1.1.3",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-firebase-analytics": "^5.0.0",
    "cordova-plugin-firebase-messaging": "^5.0.1",

**Comment by DuaneQ** [comment]
> I am receiving notification in the background and foreground for both ios and android devices. but i am unable to receive data message in ios device. Data messages are working for android but not for ios. My code is written below:
> 
> this.firebaseMessaging.onMessage().subscribe(data => {
> console.log('message data: ', JSON.stringify(data));
> this.handleNotifications(data);
> });
> this.firebaseMessaging.onBackgroundMessage().subscribe(data => {
> console.log('onBackgroundMessage data: ', JSON.stringify(data));
> this.handleNotifications(data);
> });
> 
> both subscriptions did not receiving any data message for ios.

Are you still having issues?  I can't get data on iOS
