### ISSUE TITLE
Icon is not showing in the status bar in android while getting the notification

### ISSUE THREAD

**Issue by rakeshbaral92** [chemerisuk/cordova-plugin-firebase-messaging#170]
I am trying to show notification when app is in background. But unfortunately no notification is showing as pop up and also notification icon is not showing in the status bar as well.

**Comment by chemerisuk** [comment]
Use option `forceShow` and send correct push notification:
```js
cordova.plugins.firebase.messaging.requestPermission({forceShow: true})
```
