### ISSUE TITLE
IOS Request Permission returns null

### ISSUE THREAD

**Issue by tamilselvi50** [chemerisuk/cordova-plugin-firebase-messaging#171]
We have used firebase messaging plugin in ionic project.   
this.firebaseMessaging.requestPermission().then((data: any) => {
        thi.firebaseToken =  Array.prototype.map.call(new Uint8Array(data), (x: any) => ('00' + x.toString(16)).slice(-2)).join('');

      }, (reason: any) => {
        console.log('reason hahaha' + reason);
      });

In this data always returns null.

**Comment by chemerisuk** [comment]
Use getToken for getting token value. `requestPermission` is not resolved with a token.
