### ISSUE TITLE
Foreground notifications not received in Android.background notifications working fine in Android.

### ISSUE THREAD

**Issue by mahendranthenur** [chemerisuk/cordova-plugin-firebase-messaging#174]
Thank you for the great plugin.
Foreground notifications not received in Android. background notifications working fine in Android. I followed all the example codes given, 

Am i missed anything..?

Thank you for support.

**Comment by chemerisuk** [comment]
@mahendranthenur by default when app is in foreground only onMessage callback triggered without native notifications. If you need native notifications pass forceShow option into requestPermission call.

**Comment by nupurjha** [comment]
Hi @chemerisuk ,

I am facing issue in foreground notification even I had set forceshow option into requestPermission call as you had suggested but still foreground notifications are not getting received in android.Please let me know if anything is missing.

Thanks in advance!
