### ISSUE TITLE
Task :app:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by CaturViriyananda** [chemerisuk/cordova-plugin-firebase-messaging#175]
i had this issue on cordova build

> Task :app:compileDebugJavaWithJavac FAILED
/home/vir4un/cmiew/tanyaCwk/platforms/android/app/src/main/java/by/chemerisuk/cordova/firebase/FirebaseAnalyticsPlugin.java:71: error: cannot find symbol
        bundle.putString(FirebaseAnalytics.Param.SCREEN_NAME, screenName);
                                                ^
  symbol:   variable SCREEN_NAME
  location: class Param
/home/vir4un/cmiew/tanyaCwk/platforms/android/app/src/main/java/by/chemerisuk/cordova/firebase/FirebaseAnalyticsPlugin.java:72: error: cannot find symbol
        firebaseAnalytics.logEvent(FirebaseAnalytics.Event.SCREEN_VIEW, bundle);
                                                          ^
  symbol:   variable SCREEN_VIEW
  location: class Event
/home/vir4un/cmiew/tanyaCwk/platforms/android/app/src/main/java/by/chemerisuk/cordova/firebase/FirebaseAnalyticsPlugin.java:79: error: cannot find symbol
        this.firebaseAnalytics.setDefaultEventParameters(parse(params));
                              ^
  symbol:   method setDefaultEventParameters(Bundle)
  location: variable firebaseAnalytics of type FirebaseAnalytics
/home/vir4un/cmiew/tanyaCwk/platforms/android/app/src/main/java/by/chemerisuk/cordova/firebase/FirebaseMessagingPlugin.java:89: error: cannot find symbol
        firebaseMessaging.deleteToken().addOnCompleteListener(cordova.getActivity(), task -> {
                         ^
  symbol:   method deleteToken()
  location: variable firebaseMessaging of type FirebaseMessaging
/home/vir4un/cmiew/tanyaCwk/platforms/android/app/src/main/java/by/chemerisuk/cordova/firebase/FirebaseMessagingPlugin.java:101: error: cannot find symbol
            firebaseMessaging.getToken().addOnCompleteListener(cordova.getActivity(), task -> {
                             ^
  symbol:   method getToken()
  location: variable firebaseMessaging of type FirebaseMessaging
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

FAILURE: Build failed with an exception

**Comment by chemerisuk** [comment]
Duplicates https://github.com/chemerisuk/cordova-plugin-firebase-messaging/issues/173

**Comment by hathemi** [comment]
hi, 
i have the same bug in FirebaseAnalytics , did you solve the problem ?

> Task :app:compileDebugJavaWithJavac FAILED
> /home/vir4un/cmiew/tanyaCwk/platforms/android/app/src/main/java/by/chemerisuk/cordova/firebase/FirebaseAnalyticsPlugin.java:71: error: cannot find symbol
> bundle.putString(FirebaseAnalytics.Param.SCREEN_NAME, screenName);
> ^
> symbol: variable SCREEN_NAME
> location: class Param
> /home/vir4un/cmiew/tanyaCwk/platforms/android/app/src/main/java/by/chemerisuk/cordova/firebase/FirebaseAnalyticsPlugin.java:72: error: cannot find symbol
> firebaseAnalytics.logEvent(FirebaseAnalytics.Event.SCREEN_VIEW, bundle);
> ^
> symbol: variable SCREEN_VIEW
> location: class Event
> /home/vir4un/cmiew/tanyaCwk/platforms/android/app/src/main/java/by/chemerisuk/cordova/firebase/FirebaseAnalyticsPlugin.java:79: error: cannot find symbol
> this.firebaseAnalytics.setDefaultEventParameters(parse(params));
