### ISSUE TITLE
onBackgroundMessage is firing even when the app is on foreground

### ISSUE THREAD

**Issue by akadebnath** [chemerisuk/cordova-plugin-firebase-messaging#181]
My subscription code:

```
cordova.plugins.firebase.messaging.requestPermission({forceShow: true}).then(function() {
	cordova.plugins.firebase.messaging.subscribe('all');
	cordova.plugins.firebase.messaging.subscribe(device.platform);
},
function() {
	alert('Please turn on notification from device settings to receive important communication.','');
});
```

Then I am handling the notification as below:

```
cordova.plugins.firebase.messaging.onMessage(function(payload){
  alert(payload.tab);
});

cordova.plugins.firebase.messaging.onBackgroundMessage(function(payload) {
  setTimeout(function(){$$(".tab-link[href='#"+payload.tab+"']").trigger('click');},500);
});
```

Problem is, I am still getting native notification popup from top of the screen even when the app is opened in the foreground. This is annoying particularly when someone is chatting with other person, and although they are in the app, notification pops up.

**Comment by dileepjb2** [comment]
I am using Ionic 3 but hope still helps you. I faced the same issue so I downgraded the plugin version to 1.14 and the package version to 4.15.0.it works for me and I removed **ContentAvailable: true** in firebase-admin also.if we have **ContentAvailable:true** getting 2 notifications

**Comment by akadebnath** [comment]
Thank you for the suggestion. I will try it and see. 
Yes I didn't used to have this with my previous apps, but with previous versions, popup notification would not appear.
The notification icon appeared on status bar, sound played, but no popup.
I belive when the plugin or package is updated, they are forcing the popup notification. It needs to be disabled when the app is in foreground.

**Comment by chemerisuk** [comment]
@akadebnath you should use cordova.plugins.firebase.messaging.requestPermission({forceShow: false}) to disable native popup when app is in foreground.
