### ISSUE TITLE
dependency to cordova-plugin-androidx optional

### ISSUE THREAD

**Issue by capc0** [chemerisuk/cordova-plugin-firebase-messaging#184]
when using cordova-android >= 9, the androidx plugin should officially be uninstalled (https://www.npmjs.com/package/cordova-plugin-androidx).

this plugin however has a hard dependecy. is it possible to make the dependency optional?

```
$ cordova plugin rm cordova-plugin-androidx
The plugin 'cordova-plugin-androidx' is required by (cordova-plugin-firebase-messaging), skipping uninstallation. (try --force if trying to update)
```

**Comment by chemerisuk** [comment]
cordova-plugin-androidx v3 skips installation if cordova platform >= 9
