### ISSUE TITLE
Cordova app communicates to old firebase project on app update.

### ISSUE THREAD

**Issue by rohitwtbs** [chemerisuk/cordova-plugin-firebase-messaging#185]
Hey @chemerisuk
I am running into a small problem in my Cordova app.
We have already shipped the app with firebase keys in production and now we want to change the keys pointing to a different firebase project .
But the app is still making connection with the old firebase keys and the messages triggered from new firebase account is never received.

**Comment by chemerisuk** [comment]
@rohitwtbs I haven't tested such scenario... You could try to call https://github.com/chemerisuk/cordova-plugin-firebase-messaging#deletetoken and see if it helps.
