### ISSUE TITLE
Is there a way to support this plugin to show notifications with images ?

### ISSUE THREAD

**Issue by nimishdesai1989** [chemerisuk/cordova-plugin-firebase-messaging#188]

**Comment by chemerisuk** [comment]
https://firebase.google.com/docs/cloud-messaging/android/send-image
https://firebase.google.com/docs/cloud-messaging/ios/send-image

**Comment by nimishdesai1989** [comment]
Hello @chemerisuk . Thanks for this link. We use azure devops for our CI CD build pipeline for the apps. The methods mentioned here in the email need us to manually add the extension after the platform is built on cordova and then copied to macbook for enabling the extension. Is there a plugin available that can auto configure the steps and compatible to othet firebase plugins that you provided ? I am already using the firebase analytics and fcm plugins from your repository and its awesome.
