### ISSUE TITLE
Foreground push notification arrives and then disappears from the status bar

### ISSUE THREAD

**Issue by dipanshukapoor-sirion** [chemerisuk/cordova-plugin-firebase-messaging#189]
In our application whenever the foreground notification arrives, it is displayed as a push notification on top but disappears after that.
We have added forceShow as true

**Comment by chemerisuk** [comment]
@dipanshukapoor-sirion this is expected behaviour. iOS autohides foreground notifications by default, for Android logic emulates it.

**Comment by dipanshukapoor-sirion** [comment]
Do we have some way to show local notification in such case? As user doesn't get enough time to click on the notification and it disappears

**Comment by chemerisuk** [comment]
It's not a part of this plugin. I suggest to use `forceShow:false` and trigger rich notification in `onMessage` callback using plugin for local notifications.

**Comment by dipanshukapoor-sirion** [comment]
Can you provide a small snippet on how to trigger rich notification?

**Comment by chemerisuk** [comment]
Try https://github.com/katzer/cordova-plugin-local-notifications
