### ISSUE TITLE
Can not build project with cordova-plugin-firebase-messaging library

### ISSUE THREAD

**Issue by detainee** [chemerisuk/cordova-plugin-firebase-messaging#190]
Hi everyone and Chemerisuk,
I need to using this library in OutSystems (for self-study). It like some other app with using js.
But, when I create apk app, I get the error: "Some plugins using Google Services aren't correctly configured..."
I think this may because I have not config to using this lib correctly.
Could you please give me some example project or document that guide me how to use this library, ... such as where to put google-services.json file, which function should I call first, ...
Thank you very much.
P/S: sorry to bother you, I don't know where to as this, so I post it here (issue) T-T

**Comment by philippogol** [comment]
1. create an android project on firebase cloud messaging: https://console.firebase.google.com/
2. go inside and click on the small settings gear > project settings (top left, close to Project Overview)
3.  add an android project
4. download google-servoces.json
5. add the file to the /platforms/android/app/ folder
6. on config.xml (at the root of the folder and at /app/src/main/res/xml/) add this line <platform name="android"><resource-file src="google-services.json" target="/app/google-services.json" /></platform> (not 100% sure if necessary) 

gl!
