### ISSUE TITLE
Multiple icons in statusbar

### ISSUE THREAD

**Issue by gmbad** [chemerisuk/cordova-plugin-firebase-messaging#192]
Hi!

Each message received generates 1 new icon in my statusbar.

Would it be possible to generate only 1 icon, always with the last message received?

thank you very much,

Gabriel

**Comment by chemerisuk** [comment]
@gmbad use collapse_key on server https://stackoverflow.com/questions/39886108/adding-collapse-key-in-fcm

**Comment by gmbad** [comment]
@chemerisuk 
I'll try. Thank you very much
