### ISSUE TITLE
Method onTokenRefresh does not work

### ISSUE THREAD

**Issue by Antontsyk** [chemerisuk/cordova-plugin-firebase-messaging#193]
Hello.
I use you plugin and use method onTokenRefresh for track uninstall in appsflyer, but does not work

example:
window.cordova.plugins.firebase.messaging.onTokenRefresh(() => {
    window.cordova.plugins.firebase.messaging.getToken().then((token) => {     
      window.plugins.appsFlyer.updateServerUninstallToken(token);
    });
  });

**Comment by chemerisuk** [comment]
@Antontsyk you need to add additional `firebaseMessaging.getToken` because `onTokenRefresh` callback is triggered only on token change:
```js
firebaseMessaging.getToken().then((token) => {
   window.plugins.appsFlyer.updateServerUninstallToken(token);
});

firebaseMessaging.onTokenRefresh(() => {
    firebaseMessaging.getToken().then((token) => {
        window.plugins.appsFlyer.updateServerUninstallToken(token);
    });
});
```
