### ISSUE TITLE
PHP implemantation

### ISSUE THREAD

**Issue by hro-ict** [chemerisuk/cordova-plugin-firebase-messaging#195]
I use PHP implemantation of FCM. 
I can send  message and it appears on console log. But i am not getting notification.

follow my code:
`<?php
function sendGCM($message, $id) {

$url = 'https://fcm.googleapis.com/fcm/send';

$fields = array (
        'registration_ids' => array (
                $id
        ),
        'data' => array (
                "message" => $message
        )
);
$fields = json_encode ( $fields );

$headers = array (
        'Authorization: key='."api_key",
        'Content-Type: application/json'
);

$ch = curl_init ();
curl_setopt ( $ch, CURLOPT_URL, $url );
curl_setopt ( $ch, CURLOPT_POST, true );
curl_setopt ( $ch, CURLOPT_HTTPHEADER, $headers );
curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
curl_setopt ( $ch, CURLOPT_POSTFIELDS, $fields );

$result = curl_exec ( $ch );
echo $result;
curl_close ( $ch );
}
print_r(sendGCM("test?", "device_id"));
?>`

```

**Comment by hro-ict** [comment]
`array ( $id ), 'data' => array ( "message" => $message ) ); $fields = json_encode ( $fields ); $headers = array ( 'Authorization: key='."api_key", 'Content-Type: application/json' ); $ch = curl_init (); curl_setopt ( $ch, CURLOPT_URL, $url ); curl_setopt ( $ch, CURLOPT_POST, true ); curl_setopt ( $ch, CURLOPT_HTTPHEADER, $headers ); curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true ); curl_setopt ( $ch, CURLOPT_POSTFIELDS, $fields ); $result = curl_exec ( $ch ); echo $result; curl_close ( $ch ); } print_r(sendGCM("test?", "device_id")); ?>`

**Comment by philippogol** [comment]
check this code, is working fine, just switched to this plugin and was doing some testing:

	define( 'API_ACCESS_KEY', '---');
	$registrationIds = array(_TOKEN);
	$msg = array
	(
		'body' => $message,
		'title' => $title,
		'vibrate' => 1,
		'icon' => 'ic_stat_menu_v_home',
		'image' => '',
	);
	$fields = array
	(
	'registration_ids' => $registrationIds,
	'notification' => $msg,
	'soundname' => 'default',
	);
	$headers = array
	(
	'Authorization: key=' . API_ACCESS_KEY,
	'Content-Type: application/json'
	);
	$ch = curl_init();
	curl_setopt( $ch,CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send' );
	curl_setopt( $ch,CURLOPT_POST, true );
	curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
	curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
	curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
	curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
	$result = curl_exec($ch );
	curl_close( $ch );
	echo $result;

the result looks as following:
{"multicast_id":1113111989243783710,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1631110033911119%e5552e29e5552i88"}]}

**Comment by hro-ict** [comment]
thanks man. it works
