### ISSUE TITLE
iOS Native: tried calling FirebaseMessaging.getToken, but the FirebaseMessaging plugin is not installed

### ISSUE THREAD

**Issue by neo0000** [chemerisuk/cordova-plugin-firebase-messaging#197]
I'm having an issue during runtime in iOS with the cordova-plugin-firebase-messaging. It shows a warning in the console if we open the dev tools from safari. Saying that the plugin is not installed. 

Seems also strange that during the setup I encountered an error when installing the cordova-plugin-firebase-analytics and cordova-plugin-firebase-messaging it feels like I can't install both plugins together. But even I encountered the error both plugins are visible under the plugins directory. And when I proceed to the xcode to build and run the target I manage to open the app in the emulator. Is just that there is a warning in the console that the firebase messaging is not installed.

Also, do I need a paid Apple developer account just for local debugging to use the plugin?

**Setup:**
Using unpaid apple developer account

macOS Monterey  
Platform: iOS using emulator iPhone 11 Pro
Xcode: version 13.1

packages and Frameworks including their versions:
Ionic CLI 6.18.0
cordova-res 0.15.3
cordova 10.0.0
corepack 0.10.0
native-run 1.5.0 
npm 8.1.3

Firebase related plugins installed and their versions:
cordova-plugin-firebase 2.0.5
cordova-plugin-firebase-messaging 6.1.0
cordova-plugin-firebase-analytics 6.1.0

What I have done so far:
- I already read the plugins, ionic, and firebase documentation. 
- Research in google, GitHub, StackOverflow, and other threads/forums, and tried their solution but had no luck.
- Tried to experiment also to downgrade versions of the Cordova and plugins but still no luck
- Tried also use different plugins like firebaseX and fcm. I encountered the same warning in firebaseX, and for fcm had a different problem during prepare iOS.

**Comment by noxiousmobile** [comment]
I am having the same issue. Have you resolved this one?

**Comment by noxiousmobile** [comment]
Actually I resolved it by upgrading cordova-ios.
