### ISSUE TITLE
Warning: The app gradle file must have a dependency on com.google.firebase:firebase-core for Firebase services to work as intended.

### ISSUE THREAD

**Issue by kanashin** [chemerisuk/cordova-plugin-firebase-messaging#20]
Hello!
I love this plugin, however I see the following warning when I build for android:
Warning: The app gradle file must have a dependency on com.google.firebase:firebase-core for Firebase services to work as intended.

And for IOS:
ld: library not found for -lFirebaseCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

Thanks!

**Comment by chemerisuk** [comment]
This is just a warning. According to official docs the core dependency can be absent (
https://firebase.google.com/docs/cloud-messaging/android/client)

**Comment by Raykud** [comment]
fyi: the official docs also state this: 

> Firebase now requires the app gradle file to explicitly list com.google.firebase:firebase-core as a dependency for Firebase services to work as expected.
https://developers.google.com/android/guides/releases#may_23_2018

**Comment by petermian** [comment]
so, is there a solution ?

**Comment by 1Dx** [comment]
> > so, is there a solution ?
> 
> I added a line `implementation 'com.google.firebase:firebase-core:16.0.5'` which fixed the warning

That fixed it!

**Comment by chemerisuk** [comment]
Version 1.2 now has explicit dependency on `firebase-core`

**Comment by srisachin093** [comment]
But when use 16.1.0 then this warning is occuring also...and 16.1.0 is the lastest one.

**Comment by renatodolce** [comment]
![image](https://user-images.githubusercontent.com/5089350/50341668-df8ccc80-0506-11e9-8236-ba6473a8e24a.png)
someone help me?

**Comment by Rawkush** [comment]
> implementation 'com.google.firebase:firebase-core:16.0.5

thanks, this fixed the warning

**Comment by ronifebri** [comment]
> > so, is there a solution ?
> 
> I added a line `implementation 'com.google.firebase:firebase-core:16.0.5'` which fixed the warning

where i must to add this line? sorry am a newbie

**Comment by xXLUCIFERINXx** [comment]
> > > so, is there a solution ?
> > 
> > 
> > I added a line `implementation 'com.google.firebase:firebase-core:16.0.5'` which fixed the warning
> 
> where i must to add this line? sorry am a newbie

add it in your app level build.gradle file in dependencies.

**Comment by ronifebri** [comment]
> > > > so, is there a solution ?
> > > 
> > > 
> > > I added a line `implementation 'com.google.firebase:firebase-core:16.0.5'` which fixed the warning
> > 
> > 
> > where i must to add this line? sorry am a newbie
> 
> add it in your app level build.gradle file in dependencies.

which line dependencies?
I've been in the last line but failed

**Comment by Prakashap66-com** [comment]
OMG !!! when I added this  "implementation 'com.google.firebase:firebase-core:16.0.5' ",in a new line,my error got automatically solved,Thans a lot.

**Comment by RangeshZone** [comment]
Hey users  this is just a warning .you don't need to worry about it But, if you want to resolve the warning then just add this line      **implementation 'com.google.firebase:firebase-core:16.0.7'**

Or you can Use the latest version for your dependencies 
such as :
    implementation 'com.google.firebase:firebase-auth:16.1.0'
    implementation 'com.google.firebase:firebase-database:16.1.0'
    implementation 'com.google.firebase:firebase-storage:16.1.0'
    
Hope your problem get solved by this

**Comment by undefined098** [comment]
> > > so, is there a solution ?
> > 
> > 
> > I added a line `implementation 'com.google.firebase:firebase-core:16.0.5'` which fixed the warning
> 
> where i must to add this line? sorry am a newbie

in build.gradle(app) 
dependencies
{
//HERE
implementation 'com.google.firebase:firebase-core:16.0.5
}

**Comment by tanvir-durlove** [comment]
Somehow unfortunately I didn't get my solution using only `"implementation 'com.google.firebase:firebase-core:16.0.5' "` 
after searching a lot I finally got my solution following this **Please Change your Firebase and Google Library to same version**
If you use your Assistant tool of Android Studio for automatically implement dependencies , Its possible to mismatch the version number. So in that case just make sure you use the same version of google play services and firebase.

**Comment by Michaeltetteh** [comment]
Use the latest version from the developer docs as at the time of writing the latest versions were
 implementation 'com.google.firebase:firebase-database:16.1.0'
 implementation 'com.google.firebase:firebase-core:16.0.8'
`https://firebase.google.com/support/release-notes/android`

**Comment by beck2401** [comment]
> ![image](https://user-images.githubusercontent.com/5089350/50341668-df8ccc80-0506-11e9-8236-ba6473a8e24a.png)
> someone help me?
> 
> **_Edit_**
> I found a solution, I added the plugin cordova-plugin-firebase-core and solved it.

Hey,
I have the same Problem. How can i add this plugin?
