### ISSUE TITLE
ios confilict with phonegap-plugin-push  FirebaseMessaging and 

### ISSUE THREAD

**Issue by mohamedsharaf** [chemerisuk/cordova-plugin-firebase-messaging#21]
phonegap-plugin-push uses

`    <framework src="FirebaseMessaging" type="podspec" spec="~> 2.0.0"/>
`
your plugin uses

`        <framework src="Firebase/Messaging" type="podspec" spec="~> 5.2"/>
`

this make error when installing pods as phonegape require core 4.+ and your 5.+ how this can be solved

**Comment by chemerisuk** [comment]
I don't think you should have both plugin in a project

**Comment by mohamedsharaf** [comment]
i know but when i add your firebase  analytics it also adds messaging same way this make same conflict
