### ISSUE TITLE
Breaking changes with Capacitor 4.0 and Ionic 6

### ISSUE THREAD

**Issue by iamromec** [chemerisuk/cordova-plugin-firebase-messaging#213]
Hello,

I'm trying to migrate my old app with Ionic 6. Everything is fine but when I install this plugin, the Android build fails with the following exception:

<img width="1552" alt="Screenshot 2022-08-04 at 6 06 58 PM" src="https://user-images.githubusercontent.com/50284628/182848752-3dba1a66-9da0-4b93-beda-dc04b3f50a31.png">

Here is my package.json file

<img width="399" alt="Screenshot 2022-08-04 at 6 08 14 PM" src="https://user-images.githubusercontent.com/50284628/182848918-d12666b0-02bc-4a9e-ae70-25bfe5203d46.png">

If I remove the plugin and rebuild it, it works fine. So I assume there are some issues with the plugin or compatibility with the latest capacitor version.

Please help. And let me know if you need more info.

**Comment by chemerisuk** [comment]
@iamromec it looks like capacitor doesn’t support bom dependencies yet https://github.com/ionic-team/capacitor/issues/5820#issuecomment-1204248586.

**Comment by iamromec** [comment]
Even if I downgrade to 6.1.0, it breaks and throws the following error on app launch.

<img width="1552" alt="Screenshot 2022-08-05 at 6 01 21 PM" src="https://user-images.githubusercontent.com/50284628/183077883-6bfc453d-c81d-482e-9a6d-5027e1d7cd09.png">

**Comment by iamromec** [comment]
FYI, I have tried adding all firebase plugins to get deviceToekn like firebase, firebase x, and firebase messaging. But all of these are incompatible with Capacitor 4.0.

**Comment by chemerisuk** [comment]
@iamromec try to downgrade Cordova-support-android-plugin too. The error you mentioned is connected to its latest version but previous Cordova firebase plugins should use version 1.

**Comment by iamromec** [comment]
It worked after downgrading to cordova-support-android-plugin: ^1.0.2.

Additionally, I had to do the following things in order to make it work:

- Add `android:exported="false"` to <project-root>/android/app/src/main/AndroidManifest.xml on `activity` tag

- Add `android:exported="false"` to <project-root>/android/capacitor-cordova-android-plugins/src/main/AndroidManifest.xml on `receiver` and `sender` tags

- Then I had to go to Android Studio > Refractor > Migrate to AndroidX

And then run the app. If these could be automated for Capacitor 4.0, it'd work smoothly.

**Comment by iamromec** [comment]
Downgrading to 6.1.0 worked fine in Android after downgrading the support plugin as well.

But it throws errors in iOS (Xcode) while building with the latest capacitor 4.0.

**Comment by iamromec** [comment]
Please please make this plugin work for both platforms smoothly. It's really frustrating to upgrade/downgrade for iOS/Android to build or run the app.

**Comment by chemerisuk** [comment]
@iamromec it's primary a Cordova Plugin. Ask iconic/capacitor related questions on their forum.
