### ISSUE TITLE
Error add plugin on xcode 14.0.2 / Cordova 11.0.0

### ISSUE THREAD

**Issue by mirkocentralix** [chemerisuk/cordova-plugin-firebase-messaging#217]
Howdy
I'm having a problem installing the plugin.

Install with : cordova plugin add cordova-plugin-firebase-messaging --variable IOS_FIREBASE_POD_VERSION="9.6.0"

[output.txt](https://github.com/chemerisuk/cordova-plugin-firebase-messaging/files/9878433/output.txt)

**Comment by noxiousmobile** [comment]
I have the same issue. Have you resolved this one ?

**Comment by noxiousmobile** [comment]
Actually I resolved it by upgrading cordova-ios.
