### ISSUE TITLE
No notification in Notification bar

### ISSUE THREAD

**Issue by murwa** [chemerisuk/cordova-plugin-firebase-messaging#22]
I've installed the plugin and everything seems to be working fine, however, notifications are not showing up in the notifications bar. I've tested with the foreground callback, I'm able to get the notification.

Is there anything I'm missing?

**Comment by remisture** [comment]
I don't think messages received in foreground will show in the notification bar.

**Comment by murwa** [comment]
@remisture you are right.

**Comment by JoseGeorges8** [comment]
I'm not receiving them in background either
