### ISSUE TITLE
How to set badge count ?

### ISSUE THREAD

**Issue by aravindforums1** [chemerisuk/cordova-plugin-firebase-messaging#221]
I am using cordova-plugin-firebase-messaging to get token successfully and send notification to specific device, in index.js file , under the deviceready function i set the badge count, when i onBackgroundMessage() function and onMessage() function, but count not display in mobile icon.

```
     cordova.plugins.firebase.messaging.setBadge(10);
  cordova.plugins.firebase.messaging.onMessage(function(payload) {
         cordova.plugins.firebase.messaging.setBadge(10);
    });

    cordova.plugins.firebase.messaging.onBackgroundMessage(function (payload) {
       cordova.plugins.firebase.messaging.setBadge(10);
    });
```

Any reply much appreciated.

**Comment by chemerisuk** [comment]
@aravindforums1 for background notifications you should set badge via payload property.
