### ISSUE TITLE
FCM Analystics

### ISSUE THREAD

**Issue by kalwinskidawid** [chemerisuk/cordova-plugin-firebase-messaging#234]
Hi,
Can anyone tell me if the problem is only in my configuration or is it a global (plugin) problem? I added analytics labels, tried to create campaigns (I received a notification on my phone and clicked on it). However, in the reports I only have notifications sent with no information on how many were clicked or received by subscribers.
![image](https://github.com/chemerisuk/cordova-plugin-firebase-messaging/assets/9535316/5584d1fb-0c2e-4d70-8e2f-7dcaf347456e)

**Comment by chemerisuk** [comment]
You need to add firebase analytics plugin to collect these events.
