### ISSUE TITLE
Redirect to specific page after user taps on notification?

### ISSUE THREAD

**Issue by bsprengelmeijer** [chemerisuk/cordova-plugin-firebase-messaging#237]
Is there a way to achieve this? I don't see any specific event being triggered on tap, only on receiving the message.

**Comment by mohamedmaher2021** [comment]
Did u find any solution for this ?

**Comment by bsprengelmeijer** [comment]
> Did u find any solution for this ?

I switched to [cordova-plugin-firebasex](https://github.com/dpa99c/cordova-plugin-firebasex). 

There you get the `tap` property when the user has tapped on the message. Together with additional data you can sent in your push message you can determine which page you want the user to redirect to.
