### ISSUE TITLE
Android is requesting a new permission for notification in Android 13

### ISSUE THREAD

**Issue by Eduardochimchek** [chemerisuk/cordova-plugin-firebase-messaging#239]
Android 13 introduces a new execution permission for notifications: POST_NOTIFICATIONS.

Applications that do not have this new type are not receiving notifications in background mode.

The permission that you need to declare in app manifest file appears in the following code snippet:

`<manifest ...>
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
    <application ...>
        ...
    </application>
</manifest>`

@chemerisuk 
**PLEASE UPDATE PLUGIN**

**Comment by chemerisuk** [comment]
Fixed in v8.

**Comment by Eduardochimchek** [comment]
Thank you, now everything works ok.
