### ISSUE TITLE
Increment badge in background

### ISSUE THREAD

**Issue by Genarito** [chemerisuk/cordova-plugin-firebase-messaging#24]
Is there a way to increment badge number when a notification arrives in background? Or we can increment it when user taps on the notification message only?

I tried:

```
this.firebaseMessaging.onBackgroundMessage().subscribe((notification) => {
    this.firebaseMessaging.getBadge().then((count) => {
        this.firebaseMessaging.setBadge(count + 1);
    });
});
```

But it doesn't work.

Thanks in advance

**Comment by chemerisuk** [comment]
Update badge value in your apns payload instead.
