### ISSUE TITLE
Framework 'Pods____ ' not found (iOS)

### ISSUE THREAD

**Issue by alexseyrakov** [chemerisuk/cordova-plugin-firebase-messaging#242]
After installing the plugin cordova-plugin-messaging 8.x.x , an error appears when built the project.
On version 6.x.x of the plugin works correctly.
Please, help me with some advice.

<img width="274" alt="img1" src="https://github.com/chemerisuk/cordova-plugin-firebase-messaging/assets/679952/17a14245-4dda-450f-b12b-7f4967c90c10">

on cordova-plugin-firebase-messaging 8.x.x
<img width="821" alt="img3" src="https://github.com/chemerisuk/cordova-plugin-firebase-messaging/assets/679952/2b92dad5-a8d6-495a-9b4c-b59fe3880414">

on cordova-plugin-firebase-messaging 6.x.x
<img width="842" alt="fdhfg" src="https://github.com/chemerisuk/cordova-plugin-firebase-messaging/assets/679952/cac0dc68-851c-4fd3-a898-31b93fd80ef4">

**Comment by alexseyrakov** [comment]
**package.json**

`
      "cordova-plugin-firebase-messaging": {
        "IOS_FIREBASE_POD_VERSION": "9.3.0",
        "ANDROID_FIREBASE_BOM_VERSION": "30.3.1"
      },
`

**logs in the terminal when adding a plug-in to the project** 

`
Installing "cordova-plugin-firebase-messaging" for ios
Running command: pod install --verbose

[!] The `TestApp [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-TestApp/Pods-TestApp.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `TestApp [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-TestApp/Pods-TestApp.release.xcconfig'. This can lead to problems with the CocoaPods installation
`

**Comment by jpardenoy** [comment]
What happened?
