### ISSUE TITLE
onBackgroundMessage not called after migration to capacitor

### ISSUE THREAD

**Issue by pmlodawski** [chemerisuk/cordova-plugin-firebase-messaging#245]
Hi, I migrated my iOS application to capacitor and since then `onBackgroundMessage` and `onMessage` is no longer called when sending `data` notifications. Normal notifications shows up, but also `onBackgroundMessage` and `onMessage` are not called then. No changes from server side since it was working without capacitor. Does this plugin work with capacitor? Do you have any suggestions what should I check?

**Comment by chemerisuk** [comment]
This is a Cordova plugin, it may not work with capacitor.
