### ISSUE TITLE
Push Notifications on Android 13 and higher devices

### ISSUE THREAD

**Issue by vishnuA3** [chemerisuk/cordova-plugin-firebase-messaging#246]
We are following versions

Cordova android - 12.0.1
GradlePluginGoogleServicesVersion - 4.4.0
android-targetSdkVersion - 33
cordova-plugin-firebase-messaging - 5.0.1

Issue Facing

Push notification is working in foreground and background until android 12.
From android 13 and higher we are receiving push notification only for the 1st time when the app is in foreground.
**We are not receiving notification once we close/ minimize/ in background , the app basically stops receiving the notification once app moves to background.**

We are using Firebase Cloud Messaging token based authentication via AWS SNS service.
As per AWS SNS service the message pushed successfully but not getting notified.
We have **enabled the allow notification permission** in device for the respective app.

This issue is a showstopper for us , could you kindly guide us to address this issue.

**Comment by Sathyavathi2018** [comment]
Hi, Is there any update on this ticket?
