### ISSUE TITLE
notifications do not open the app

### ISSUE THREAD

**Issue by marcosandrade22** [chemerisuk/cordova-plugin-firebase-messaging#25]
[english]
Hello, I implemented this plugin and the notifications are working perfectly but when they trigger they do not open the app.
Can you help me with this?

[português]
Olá, eu implementei este plugin e as notificações estão funcionando perfeitamente porém ao acionar elas não abrem o app.
Consegue me ajudar nesta questão?

**Comment by chemerisuk** [comment]
I have never experienced such a problem. What payload have you been sending?
