### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by deekshithp45** [chemerisuk/cordova-plugin-firebase-messaging#26]
Warning: The app gradle file must have a dependency on com.google.firebase:firebase-core for Firebase services to work as intended.

**Comment by iRahulGaur** [comment]
add firebase dependencies from the menu -> 
Click Tools > Firebase to open the Assistant window.
Click to expand one of the listed features (for example, Firebase Core), then click the Get Started tutorial to connect to Firebase and add the necessary code to your app.

**Comment by chemerisuk** [comment]
This is just a warning. According to official docs the core dependency can be absent (
https://firebase.google.com/docs/cloud-messaging/android/client)
