### ISSUE TITLE
After Installing Plugin: Cannot build from CLI (xcworkspace works perfectly)

### ISSUE THREAD

**Issue by jpgilchrist** [chemerisuk/cordova-plugin-firebase-messaging#34]
First and foremost, the library seems great and frankly I'm not sure if this is the plugin, some environment setup issue, or what, but after installing this plugin I am no longer able to build for iOS from the CLI. i.e., `cordova run ios`. If I open xcworkspace and run/build/archive it works perfectly. 

I have done about 2 days of research into various things like Cocoapods, etc. in order to try and figure it out, but there's not much information on them problem at hand. 

I found an SO post saying to modify the pods .m files to reference the relative path of the linked libraries, but that's just crazy. And all the other configuration such as setting the Header Search Paths seems correct... the error I'm getting at the moment is:

FIRNetwork.m fatal error GoogleToolboxForMac/GTMNSData+zlib.h not found

Again, your code/plugin is working great! I'm just hoping you may have had some insight into similar setup issues. If you don't, then feel free to close and ignore. I'll also be creating a SO post.

**Comment by LimitTech** [comment]
Hello!

Have been solved yet?

Thanks!

**Comment by jpgilchrist** [comment]
@LimitTech no it hasn't, but see https://github.com/apache/cordova-ios/issues/394 

There are outstanding, known issues with using cocoapods we had to use cordova-plugin-firebase as our plugin of choice because it doesn't use cocoapods. Instead it opts to include the source files along with the package. 

The issue with that option is that it makes it hard to integrate with other firebase plugins because the versions may not be compatible.

**Comment by chemerisuk** [comment]
[PR with the fix for cordova cli](https://github.com/apache/cordova-ios/pull/398) was merged, so I believe the issue will be resolved in the next release.
