### ISSUE TITLE
Plugin doesn't support this project's cordova-android version. cordova-android: 6.4.0, failed version requirement: >=7.0.0

### ISSUE THREAD

**Issue by goodspeed666** [chemerisuk/cordova-plugin-firebase-messaging#38]
Hi,

I install cordova-plugin-firebase-messageing@1.1.4 in the meteor@1.7.0.5.
When I run build, it shown below.

```
%% Plugin doesn't support this project's cordova-android version. cordova-android: 6.4.0, failed version requirement: >=7.0.0
%% Skipping 'cordova-plugin-firebase-messaging' for android
```
My cordova version is 8.0.0.

I can't find the `cordova-android` plugin.
Anyone have idea ?

Thank you.

**Comment by chemerisuk** [comment]
You have to upgrade Cordova-android version (not cli)
Cordova platform rm Android
Cordova platform add android@latest

**Comment by chemerisuk** [comment]
You have to upgrade Cordova-android version (not cli)
Cordova platform rm Android
Cordova platform add android@latest

**Comment by goodspeed666** [comment]
Hi @chemerisuk ,

I cannot use `cordova platform add android@latest`.
When I use meteor build code, it will be reset to default(6.4.0).

May I know, what's version can be used in the 6.4.0 ?

Thank you.

**Comment by chemerisuk** [comment]
Try versions before v1

**Comment by goodspeed666** [comment]
Hi @chemerisuk,

When I use the 0.14.0, it can not be build by meteor@1.7.0.5.
So I change another fcm plugin.

Thank you.
