### ISSUE TITLE
Cordova-plugin-firebase-messaging dont work with google plus auth

### ISSUE THREAD

**Issue by ghost** [chemerisuk/cordova-plugin-firebase-messaging#39]
Hi!

I have been try to implement google plus auth in firebase, i made it, but when i installed this plugin everything stopped working, i dont know what happen, may be, the problema is in project.properties in android platform but i cant fix it.
help please.

Sorry for my english.

**Comment by jfbourne** [comment]
Can you post the error you are getting? I am able to use both okay.

**Comment by calebeaires** [comment]
I think I have the same issue, but for more detail it could be a gradle conflit when the app has plugins that use different google play services. Make sense? How to fix this conflit?
