### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac' import com.google.firebase.iid.InstanceIdResult;

### ISSUE THREAD

**Issue by wmenegali** [chemerisuk/cordova-plugin-firebase-messaging#40]
Hey! Just installed the plugin on my app and started getting the following error when trying to compile:

`(node:10652) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\willi\Documents\pip-app\platforms\android\app\src\main\java\by\chemerisuk\cordova\firebase\FirebaseMessagingPlugin.java:18: error: cannot find symbol
import com.google.firebase.iid.InstanceIdResult;
                              ^
  symbol:   class InstanceIdResult
  location: package com.google.firebase.iid
C:\Users\willi\Documents\pip-app\platforms\android\app\src\main\java\by\chemerisuk\cordova\firebase\FirebaseMessagingPlugin.java:57: error: void cannot be dereferenced
            .addOnCompleteListener(cordova.getActivity(), new OnCompleteListener<Void>() {
            ^
C:\Users\willi\Documents\pip-app\platforms\android\app\src\main\java\by\chemerisuk\cordova\firebase\FirebaseMessagingPlugin.java:72: error: void cannot be dereferenced
            .addOnCompleteListener(cordova.getActivity(), new OnCompleteListener<Void>() {
            ^
C:\Users\willi\Documents\pip-app\platforms\android\app\src\main\java\by\chemerisuk\cordova\firebase\FirebaseMessagingPlugin.java:94: error: cannot find symbol
            .addOnCompleteListener(cordova.getActivity(), new OnCompleteListener<InstanceIdResult>() {
                                                                                 ^
  symbol:   class InstanceIdResult
  location: class FirebaseMessagingPlugin
C:\Users\willi\Documents\pip-app\platforms\android\app\src\main\java\by\chemerisuk\cordova\firebase\FirebaseMessagingPlugin.java:96: error: cannot find symbol
                public void onComplete(Task<InstanceIdResult> task) {
                                            ^
  symbol: class InstanceIdResult
C:\Users\willi\Documents\pip-app\platforms\android\app\src\main\java\by\chemerisuk\cordova\firebase\FirebaseMessagingPlugin.java:93: error: cannot find symbol
        FirebaseInstanceId.getInstance().getInstanceId()
                                        ^
  symbol:   method getInstanceId()
  location: class FirebaseInstanceId
C:\Users\willi\Documents\pip-app\platforms\android\app\src\main\java\by\chemerisuk\cordova\firebase\FirebaseMessagingPluginService.java:25: error: method does not override or implement a method from a supertype
    @Override
    ^`

Any ideas on what could be happening?

**Comment by Genarito** [comment]
From an email in response for my question in the forum about this problem:

> I would suggest updating (or downgrading) the customer gradle services version in your application and seeing if an update or downgrade provides the necessary files for the messaging plugin to run

Hope it helps
