### ISSUE TITLE
How to setup up the plugin to provide APNs token on iOS instead of the FCM token.

### ISSUE THREAD

**Issue by sqzbx** [chemerisuk/cordova-plugin-firebase-messaging#42]
Hello...

As the title says... Is there a way to get the APNs token when using the plugin on iOS builds?

Edit:
`requestPermission()` on iOS just gives `{}`

**Comment by mohamedsharaf** [comment]
remove 
        <resource-file src="GoogleService-Info.plist" />

from config.plist

**Comment by sqzbx** [comment]
> remove
> from config.plist
Thanks for the reply but remove what? Im thinking you meant the GoogleService-Info.plist  ???

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-plugin-firebase-messaging#requestpermission

The method resolves with APNS token.

**Comment by sqzbx** [comment]
> https://github.com/chemerisuk/cordova-plugin-firebase-messaging#requestpermission
> 
> The method resolves with APNS token.



Hi... Thanks... But thats the problem, the `requestPermission()` just gives out `{}`

Here my code btw...

```
var perm = await this.fcm.requestPermission().then(
  (reg: any) => {
       // `reg` = { }
       // backend call stuffs
  }
);
```

**Comment by chemerisuk** [comment]
Value returned as ArrayBuffer. You can convert it into string via function like below
```js
function ab2str(buf) {
  return String.fromCharCode.apply(null, new Uint16Array(buf));
}
```
Read https://developers.google.com/web/updates/2012/06/How-to-convert-ArrayBuffer-to-and-from-String

**Comment by sqzbx** [comment]
Tried it... I am getting `춶莽중ᙔ丢궇⃌ᢩ뇡꺡ꉬ聃쪏` when I run the ArrayBuffer through ab2str function. Not sure where to again from here. I've even tried to change `Uint16Array` to `Uint8Array` and `Uint32Array` but still getting a string I am not able make use of...

I have also tried to use another plugin and the token i can get is `{"registrationId":"b6cdbd8311c95416224ef4f687ad1cedcc20a918e1b1daeda1ae6ca243808fca","registrationType":"APNS"}` though using the other plugin i managed to get the apns token. I still pretty much prefer to use this plugin because its so much easier to use...

**Comment by chemerisuk** [comment]
The article has reference to the [TextDecoder API](https://developers.google.com/web/updates/2014/08/Easier-ArrayBuffer-String-conversion-with-the-Encoding-API). Try to use the code below:
```js
var dataView = new DataView(buf);
var decoder = new TextDecoder("ascii");
var decodedString = decoder.decode(dataView);
```

**Comment by sqzbx** [comment]
```
import encoding from 'text-encoding';

...

this.fcm.requestPermission().then(
  (token: any) => {
    console.log('token:', token, JSON.stringify(token));
    // token = [object ArrayBuffer] { }

    const decoder = new encoding.TextDecoder('ascii');

    var a_token = decoder.decode(token);
    console.log('a_token:', a_token, JSON.stringify(a_token));
    // a_token: �H�I�-�3\^\m���1�L�Dn`w߆�A�)\^[W��a "�H�I�-�3\u001cm���1�L�Dn`w߆�A�)\u001bW��a"

    var dataView = new DataView(token);
    var b_token = d.decode(dataView);
    console.log('b_token:', b_token, JSON.stringify(b_token));
    // b_token: �H�I�-�3\^\m���1�L�Dn`w߆�A�)\^[W��a "�H�I�-�3\u001cm���1�L�Dn`w߆�A�)\u001bW��a"

  } 
);
```

Also tried changing removing the `'ascii'` and also not providing it, but both produced almost same result as the code above, token result from decoding is not something I can make use of...

**Comment by chemerisuk** [comment]
I looked at how the string token is usually created in Objective C. It seems like each byte is converted as hex one by one. Try to post here a result of `buf2hex`:
```js
function buf2hex(buffer) { // buffer is an ArrayBuffer
  return Array.prototype.map.call(new Uint8Array(buffer), x => ('00' + x.toString(16)).slice(-2)).join('');
}
```

**Comment by cristianfd** [comment]
Hi, as I understand the first post `requestPermission() on iOS just gives {}`. A few days ago I had the same problem and found in other issue (i dont remember) that the way to fix this is to remove the repo plugin `npm remove cordova-plugin-firebase-messaging` and do `npm i -S git+https://github.com/chemerisuk/cordova-plugin-firebase-messaging.git` (I use ionic).
With that change, requestPermission now return the token (at least do not fails with nil or empty object).
I hope this helps.

**Comment by sqzbx** [comment]
> I looked at how the string token is usually created in Objective C. It seems like each byte is converted as hex one by one. Try to post here a result of `buf2hex`:
> 
> ```js
> function buf2hex(buffer) { // buffer is an ArrayBuffer
>   return Array.prototype.map.call(new Uint8Array(buffer), x => ('00' + x.toString(16)).slice(-2)).join('');
> }
> ```

This solved my problem. Thank you very much...
Are you going to implement changes to the plugin itself for this problem not to occur?
Thanks again...

**Comment by chemerisuk** [comment]
@sqzbx I think it's better to have a separate method for getting APNS token which accepts optional argument `type` to define output format. But this is probably for a future release.

**Comment by sqzbx** [comment]
> @sqzbx I think it's better to have a separate method for getting APNS token which accepts optional argument `type` to define output format. But this is probably for a future release.

Great! Thanks again. Im going to close this issue now...
