### ISSUE TITLE
fatal error: module 'Firebase' not found @import Firebase;  ~~~~~~~^~~~~~~~ 1 error generated.

### ISSUE THREAD

**Issue by chanra** [chemerisuk/cordova-plugin-firebase-messaging#46]
fatal error: module 'Firebase' not found
@import Firebase;
 ~~~~~~~^~~~~~~~
1 error generated.

Please help i have problem to build on ios, which i don't know what caused the issue.

**Comment by darshanakkhichi** [comment]
Hey, @chanra did you found any solution?

**Comment by dMontesAld** [comment]
Hi, is it fixed?

**Comment by darshanakkhichi** [comment]
No it's not. I'm still facing the issue.

**Comment by dMontesAld** [comment]
Your issue is with Cordova 7.1.2?

**Comment by darshanakkhichi** [comment]
This is with Cordova 8.0.0 .

**Comment by dMontesAld** [comment]
Thanks.

**Comment by onkeyi** [comment]
1) check  pod version 
sudo gem uninstall -n /usr/local/bin cocoapods
sudo gem install -n /usr/local/bin cocoapods:1.4.0

2) ionic cordova platform remove ios

3) ionic cordova platform add ios

4) cd platforms/ios

5) pod install
