### ISSUE TITLE
No revokeToken method

### ISSUE THREAD

**Issue by BradyShober** [chemerisuk/cordova-plugin-firebase-messaging#48]
The documentation lists a revokeToken method for revoking the FCM token but there is no revokeToken method in the FirebaseMessaging class. We are using version 1.1.4 of the cordova plugin.

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-plugin-firebase-messaging/blob/master/src/android/FirebaseMessagingPlugin.java#L85
https://github.com/chemerisuk/cordova-plugin-firebase-messaging/blob/master/src/ios/FirebaseMessagingPlugin.m#L81

**Comment by BradyShober** [comment]
I saw it was there in the source here, but it is not working in our code.
When we try to run
`this.firebaseMessaging.revokeToken()`
we get Property 'revokeToken does not exist on type 'FirebaseMessaging'
I have confirmed looking at the files in node_modules that the revokeToken method is not present

**Comment by Titoune** [comment]
I think you are in the wrong place, look here instead : [https://github.com/ionic-team/ionic-native](url)
 Ionic has not written this feature yet. Just wait and see.

**Comment by BradyShober** [comment]
@Titoune I think you are right, thank you for pointing me in the right direction. My apologies, that should have occurred to me.
