### ISSUE TITLE
Update Firebase/Core dependancy.

### ISSUE THREAD

**Issue by cairinmichie** [chemerisuk/cordova-plugin-firebase-messaging#50]
I get the following when installing the app:

```
cordova-plugin-firebase-messaging depends on Firebase/Core@~> 5.0, which conflicts with another plugin. Firebase/Core@~> 5.6 is already installed and was not overwritten.
```

I only use your firebase plugins.

**Comment by cairinmichie** [comment]
I also don't receive any Push notifications on iOS. Not sure if this would be the cause. I have set it up and have used it before and it worked. But not anymore.

**Comment by harishintimetec** [comment]
I am also facing the same issue with below plugins,
cordova-plugin-firebase-messaging
cordova-plugin-firebase-crashlytics
cordova-plugin-firebase-dynamiclinks

Please help me out and let me know more information needed.

**Comment by chemerisuk** [comment]
Run `pod update` from `platforms/ios`

**Comment by Azotgen** [comment]
@chemerisuk 

I have the same problem and this command seems to be working if you build it on your machine.
But how can I solve this issue if I use Ionic package build?
Thanks.
