### ISSUE TITLE
Add firebase-iid:17.0.+ to the dependencies

### ISSUE THREAD

**Issue by Thomasbehan** [chemerisuk/cordova-plugin-firebase-messaging#52]
Add firebase-iid to the dependencies will prevent the following error which causes the plugin to crash apps on some devices:

`Fatal Exception: java.lang.NoSuchMethodError
No static method zzac()Lcom/google/firebase/iid/zzap; in class Lcom/google/firebase/iid/zzap; or its super classes (declaration of 'com.google.firebase.iid.zzap' appears in base.apk)
android.app.ActivityThread.handleServiceArgs`

I've manually added this to my app but it would be great to get it into the plugin itself

**Comment by chemerisuk** [comment]
firebase-messaging library depends on firebase-iid. You don't need to add it directly.
