### ISSUE TITLE
Is OnMessage() working?

### ISSUE THREAD

**Issue by Axdron** [chemerisuk/cordova-plugin-firebase-messaging#55]
Hi there, I'm using this plugin with Ionic 4, and when I subscribe to the onMessage method, I never get a return.

I am using this code in the Background message:
 this.firebaseMessaging.onBackgroundMessage().pipe(tap(msg => { alert("Recebida em back" + JSON.stringify(msg)) 
    })).subscribe()

It's working well, when I tap the notification, the app opens and I can see the notification parameters in the alert.

Doing the same with the onMessage(), doesn't work. Only subscribing to the message doesn't fire too:
  this.firebaseMessaging.onMessage().subscribe(() => { alert ('Recebi')})

**Comment by RTK** [comment]
I think that's an Android only problem. Can you confirm my assumption, @Axdron ?

**Comment by Axdron** [comment]
Hi @RTK , yes, I`m facing the problem in Android. I`m unable to deploy to iOS to see if it happens too...

**Comment by RTK** [comment]
> Hi @RTK , yes, I'm facing the problem in Android. I'm unable to deploy to iOS to see if it happens too...

I tested the functionality on iOS and, as I assumed it works. It's an Android only problem. I try to track down the issue and may open a pull-request.

**Comment by RTK** [comment]
My research revealed, that the service + intent-filter in the AndroidManifest.xml were missing. @chemerisuk  I think that the <custom-config> tag in the plugin.xml does not work the way it should.

@Axdron for a quickfix you can add this block to your config.xml

```
<platform name="android">
        <config-file target="AndroidManifest.xml" parent="/manifest/application">
            <service android:name="by.chemerisuk.cordova.firebase.FirebaseMessagingPluginService">
                <intent-filter>
                    <action android:name="com.google.firebase.MESSAGING_EVENT"/>
                </intent-filter>
            </service>
        </config-file>
</platform>
```

**Comment by Axdron** [comment]
@RTK Thank you so much! It worked as expected. I also had to add xmlns:android to my widget tag: 

`<widget id="com.myproject" version="0.5.1" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">
 `

**Comment by tmk1991** [comment]
Not getting either event subscription to fire for onMessage() or onBackgroundMessage(). 

I'm receiving tokens okay and the device is getting push notifications in the operating system when i send them through the firebase web console. Tapping on the notification and the alert for foreground notifications also not firing. 

`this.messaging.onBackgroundMessage().pipe(
        tap(message => {
          // handle message
          console.log(message);
          alert('push notification');
        })
      ).subscribe();`

`this.messaging.onMessage().pipe(
        tap(message => {
          // handle message
          console.log(message);
          alert('foreground notification');
        })
      ).subscribe();`

**Comment by chemerisuk** [comment]
> Tapping on the notification and the alert for foreground notifications also not firing.
I don't think the alert should be displayed, because you get notification in background in this case. 

Learn https://firebase.google.com/docs/cloud-messaging/concept-options

**Comment by tmk1991** [comment]
Hi @chemerisuk  - Let me re-clarify. I'm not getting either observable to fire. I'm not able to see the message data at all on either `onMessge` or `onBackgroundMessage`.

**Comment by tmk1991** [comment]
I've tried both the ionic native wrapper:
this.messaging.onBackgroundMessage().pipe(
        tap(message => {
          // handle message
          console.log(message);
          alert('push notification');
        })
      ).subscribe();

And calling the plugin direct: 
(<any>window).plugins.firebase.messaging.onBackgroundMessage(function(payload) {
        console.log('New bkg FCM message: ', payload);
        alert(JSON.stringify(payload));
      });

Neither log or alert()...

**Comment by tmk1991** [comment]
Disregard.
Had an issue saving the user's FCM token to my DB that was throwing the error.
