### ISSUE TITLE
Notification display when app in Foreground

### ISSUE THREAD

**Issue by b-remi** [chemerisuk/cordova-plugin-firebase-messaging#56]
Hi,

First I will thanks the author for this great plugins. I have no really problem with this.

I just want to know if somebody has a solution for displaying the notification icon in the status bar even if the application is in foreground.

I saw many over application (native) who can make this. 
Maybe there is an action to perform on notification received, 
or maybe an option to add in the firebase send data...

**Comment by chemerisuk** [comment]
You should create an ongoing message in Android to add such icon. It is not connected with FCM.

**Comment by b-remi** [comment]
Ok, thanks for your response.
I will look at how works the ongoing message, I supposed that this plugin does not have this feature.
