### ISSUE TITLE
Clear Notifications in Notification bar

### ISSUE THREAD

**Issue by AitorAppCoder** [chemerisuk/cordova-plugin-firebase-messaging#57]
When user doesn't tap the notifications, they stay in the notification bar. Opening the app doesn't close them and it seams like there is no other way to do it. 
Is there a way?

**Comment by chemerisuk** [comment]
This is not implemented yet.

**Comment by liam-lime** [comment]
When do you plan to add support for this functionality?

> This is not implemented yet.

When do you plan to add support for this functionality? Any News?

**Comment by maxymczech** [comment]
Do you plan to support this?

**Comment by maxymczech** [comment]
@liam-lime This seems to be a simple fix, I have forked and implemented it for Android, tested - works fine: https://github.com/maxymczech/cordova-plugin-firebase-messaging
I have no experience whatsoever with ios Objective C, will test it on some iOS devices later today and if it works will create pull request.

**Comment by maxymczech** [comment]
P. S. I have added function `clearMessages` to the plugin, you might want to call it in `onResume` handler.

**Comment by maxymczech** [comment]
#161

**Comment by chemerisuk** [comment]
Published in v4.4.2
