### ISSUE TITLE
Receiving queued data messages when application is started

### ISSUE THREAD

**Issue by Alexxino7** [chemerisuk/cordova-plugin-firebase-messaging#58]
It is not clear to me whether this plugin is supposed to handle the following use case.

Application is closed. Server sends a data message[1] to this particular device(or to all devices). The application is then opened but the previously sent message is not received.

Is the plugin supposed to permit this? Is this something not related to the plugin?
Is there another away to receive data messages sent while the application was closed?

Thanks,

[1] https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages

**Comment by chemerisuk** [comment]
@Alexxino7 it’s possible, but you have to write java code.
