### ISSUE TITLE
Receiving notification but notification onBackgroundMessage not getting notifications in Notification bar

### ISSUE THREAD

**Issue by JoseGeorges8** [chemerisuk/cordova-plugin-firebase-messaging#59]
I receive the onBackgroundMessage when my app is on the background (I can see it while inspecting my device inside the chrome console) but I'm not getting a notification in the notification bar. Also, if I send notifications through firebase console I do see the notification bar

**Comment by CiriousJoker** [comment]
I have exactly the opposite problem... Notification shows up, but callback isn't triggered :(

**Comment by chemerisuk** [comment]
@JoseGeorges8 if app is in foreground you won't see an icon in notification bar. Only onMessage is triggered. This is expected behavior.

@CiriousJoker callback is triggered if user clicks on notification.

**Comment by CiriousJoker** [comment]
But it isn't ...
Also, why would that be the expected behavior? Then, the user would have to interact with the notification to receive a chat message. What of he opens the app without clicking on the notification first?

**Comment by bobobobo** [comment]
I am also wondering how to handle if the user opens the app without clicking the notification.

**Comment by CiriousJoker** [comment]
Ok, I figured it out, it works perfectly now. Read the fcm docs about message types. There are notification and data messages. Only data messages are shown in onBackground but don't trigger a notification
