### ISSUE TITLE
setBadge() does not work with incrementing variable

### ISSUE THREAD

**Issue by JakenHerman** [chemerisuk/cordova-plugin-firebase-messaging#60]
Unless I am just using this very improperly, the `setBadge` function does not seem to be working when a variable is passed in. I can call `cordova.plugins.firebase.messaging.setBadge(5)`, and when I get a notification in the background, the badge is set to 5. 

However, I attempted to set a variable that won't get reset to 0 until a certain function is called in my index.js file that will tally up the amount of unread notifications, like so:

`var notificationCount = 0;`

Then call setBadge() like so:

`cordova.plugins.firebase.messaging.setBadge(++notificationCount)`

Now when I get a notification, the badge only updates on the first notification I receive. All other notifications do not seem to call this function. 

Is there a better way to tally the amount of notification I've received since opening the app?

**Comment by chemerisuk** [comment]
Check your js code, this issue is not related to this plugin.
