### ISSUE TITLE
Closing the app via force-close / recents swipe prevents messages from being delivered

### ISSUE THREAD

**Issue by CiriousJoker** [chemerisuk/cordova-plugin-firebase-messaging#62]
OnBackgroundMessage doesn't trigger when I (force) close the app.

This shouldn't be that way, as Apps like WhatsApp also manage to keep running to receive messages.

Is there any possible fix in the near future for this?

**Comment by chemerisuk** [comment]
If app is closed, only notification messages are delivered to the tray. When you click on such notification app starts and OnBackgroundMessage is triggered.

**Comment by CiriousJoker** [comment]
Yes, but I send data notifications. Those are delivered even when the app is in the background. However, when I force close the app, it doesn't trigger anymore.

**Comment by CiriousJoker** [comment]
@chemerisuk Is there any chance you can fix this issue?

**Comment by chemerisuk** [comment]
OnBackgroundMessage callback is registered in your CordovaActivity webview. If user or OS kills webview process the callback can't be received.

In order to do that you have to create a foreground service on Android and register FCM listeners in java code. You can't receive such callbacks in javascript.

**Comment by CiriousJoker** [comment]
So you're saying there's no way for any cordova plugin to solve this problem since killing the app also kills the js message handler, even if the service to receive the messages is restarted?

**Comment by CiriousJoker** [comment]
@chemerisuk 
What if I implemented something like this:
1. Whenever a message arrives, your plugin displays the notification in the style I want
2. When instance.sendNotification fails (because the app is in the background), the notification is stored in a queue
3. When the app opens (deviceready is fired), a plugin method is called that sends all queued notifications back to the app

I think this would be a far more robust approach to fcm. However, I have no clue how to implement smth. like this in iOS :(

Do you think this will work? If so, I'll submit in my pull requests when I'm done (without 1.).

**Comment by CiriousJoker** [comment]
@chemerisuk 
Turns out it works pretty well for me.
Messages are stored in a simple Paper queue (new dependency this: https://github.com/pilgr/Paper/).
The queue is executed as soon as the onMessage() handler is attached.
If you want a pull request, reopen this.
