### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by myname1614** [chemerisuk/cordova-plugin-firebase-messaging#70]
after creating blank ionic project & commands
ionic cordova plugin add cordova-plugin-firebase-messaging
npm install @ionic-native/firebase-messaging
ionic cordova build android
I see:
`> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
D8: Program type already present: android.support.v4.app.FrameMetricsAggregator$FrameMetricsApi24Impl$1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.FrameMetricsAggregator$FrameMetricsApi24Impl$1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
36 actionable tasks: 12 executed, 24 up-to-date
/home/user/projects/test2/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/user/projects/test2/platforms/android/app/src/main/java/by/chemerisuk/cordova/support/ReflectiveCordovaPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
D8: Program type already present: android.support.v4.app.FrameMetricsAggregator$FrameMetricsApi24Impl$1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.FrameMetricsAggregator$FrameMetricsApi24Impl$1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
[ERROR] An error occurred while running subprocess cordova.

        cordova build android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.`

**Comment by junior-anzolin** [comment]
I have the same problem

**Comment by rulon** [comment]
try to add this code to file:
/platforms/android/project.properties

`cordova.system.library.6=com.android.support:preference-v14:28.0.0`

instead of the number 6, substitute your next in order.
I don't know what it does, but it has helped me so far, after a day of googling.

**Comment by myname1614** [comment]
try to add this code to file:
/platforms/android/project.properties

`cordova.system.library.6=com.android.support:preference-v14:28.0.0`

instead of the number 6, substitute your next in order.
I don't know what it does, but it has helped me so far, after a day of googling.
