### ISSUE TITLE
Allow setting foreground display options

### ISSUE THREAD

**Issue by adamduren** [chemerisuk/cordova-plugin-firebase-messaging#74]
It would be beneficial to be able to control whether or not a notification received while the app is in the foreground should be displayed by the OS vs in app. Currently the option for the completion handler as referenced below is set to none so in order for anything to be done with the notification extra programming on the app side is needed to present the notification.

https://github.com/chemerisuk/cordova-plugin-firebase-messaging/blob/dcee15ff92a73a4e06979940d14015b2de977075/src/ios/FirebaseMessagingPlugin.m#L219-L223

[Here](https://stackoverflow.com/a/44939581/610775) is an answer explaining how to achieve the result. We would need to add a method to the plugin to set the options. Another alternative would be a cordova preference.

@chemerisuk what are your thoughts on the issue?

**Comment by adamduren** [comment]
Something similar like [this](https://stackoverflow.com/a/38451582/610775) would be needed for android

**Comment by chemerisuk** [comment]
@adamduren yep, I was thinking about this as well. phonegap-push-plugin has option `android.forceShow` for this kind of behavior (not sure why there is no such an option for iOS). 

`UNNotificationPresentationOptionNone` is supported only in iOS 10+, so we should wait for the next release where minimum iOS SDK will be 10. This option has 4 different values supported natively - Badge, Alert, Sound. For consistency Android implementation should support all those values as well.

My current vision is that new option `forceShow` should be added to requestPermission() call:
```js
cordova.plugins.firebase.messaging.requestPermission({forceShow: ["alert", "sound"]});
```

**Comment by adamduren** [comment]
@chemerisuk  Sounds reasonable to me. I might be able to make a pull request for this if you would like. 

Do you think it should still forward the notification to the JS side? It seems to me that it would not hurt to do so as the developer would still have to take action with it if they wanted to.

**Comment by chemerisuk** [comment]
@adamduren please go ahead with the PR - start from the latest commit in v2 branch.

I don't think this option should suppress JS handlers. It looks confusing in this way. Moreover notification might have additional data fields that require separate processing on JS side.

**Comment by chemerisuk** [comment]
@adamduren I've implemented iOS part. Let me know if I can help you with Android.

**Comment by adamduren** [comment]
@chemerisuk I should be able to get to it this week.

**Comment by chemerisuk** [comment]
@adamduren any progress on the task?

**Comment by adamduren** [comment]
@chemerisuk My apologies, thank you for implementing this. I've gotten unexpectedly swamped with work related tasks.
