### ISSUE TITLE
breaking change of google broke my app

### ISSUE THREAD

**Issue by eeerrrttty** [chemerisuk/cordova-plugin-firebase-messaging#82]
FAILURE: Build failed with an exception.

* What went wrong:
In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[17.1.
0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

Dependency failing: com.google.firebase:firebase-messaging:17.4.0 -> com.google.firebase:firebase-iid@[17.1.0], but fire
base-iid version was 17.1.2.

The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
ifact with the issue.
-- Project 'app' depends onto com.google.firebase:firebase-core@16.0.+
-- Project 'app' depends onto com.google.firebase:firebase-messaging@17.4.+

**Comment by danielprrazevedo** [comment]
```
ionic cordova plugin rm cordova-plugin-firebase-messaging
ionic cordova plugin add cordova-plugin-firebase-messaging --variable ANDROID_SUPPORT_VERSION=26.1
```
