### ISSUE TITLE
Default FirebaseApp is not initialized in this process

### ISSUE THREAD

**Issue by mmikrut** [chemerisuk/cordova-plugin-firebase-messaging#83]
Hi, I'm having the issue similary to #27

I'm executing following code onDeviceReady
```
     // Initialize Firebase
        console.debug('app.onDeviceReady - firebaseConfig:',firebaseConfig);
        const fbapp = firebase.initializeApp(firebaseConfig);
        console.debug('app.onDeviceReady - fbapp:',fbapp);
        if ( typeof fbapp === 'object')
          setTimeout( () => {
            cordova.plugins.firebase.messaging.getToken()
                .then( token => {console.log('TOKEN:', token);})
                .catch( e => {console.log('ERROR',e);});
          }, 5000);

```          

Output is:

> 11:43:11.308 index.js:26 app.onDeviceReady()
> 11:43:11.308 index.js:41 app.onDeviceReady - firebaseConfig: Object
> 11:43:11.316 index.js:43 app.onDeviceReady - fbapp: Object
> 
> 11:43:16.322 index.js:48 ERROR Default FirebaseApp is not initialized in this process com.testapp.pro.dev. Make sure to call FirebaseApp.initializeApp(Context
> 

Here is my test environemtn:

```
firebase-app.js:  6.0.2 (also tested with 5.11.1)
  
    "cordova-plugin-firebase-messaging": {
      "FIREBASE_CORE_VERSION": "16.0.+",
      "FIREBASE_MESSAGING_VERSION": "18.0.+",
      "ANDROID_SUPPORT_VERSION": "26.1",
    },

  
  "plugin_metadata": {
    "cordova-plugin-app-event": "1.2.1",
    "cordova-plugin-device": "2.0.2",
    "cordova-plugin-background-mode": "0.7.2",
    "cordova-plugin-badge": "0.7.4",
    "cordova-plugin-browsertab": "0.2.0",
    "cordova-plugin-buildinfo": "2.0.2",
    "cordova-plugin-console": "1.1.0",
    "cordova-plugin-file": "6.0.1",
    "cordova-support-android-plugin": "1.0.1",
    "cordova-support-google-services": "1.3.1",
    "cordova-plugin-firebase-messaging": "2.1.0",
    "cordova-plugin-geolocation": "4.0.1",
    "cordova-plugin-inappbrowser": "3.0.0",
    "cordova-plugin-media": "5.0.2",
    "cordova-plugin-vibration": "3.1.0",
    "cordova-plugin-whitelist": "1.3.3",
    "cordova-universal-links-plugin": "1.2.1"
  }

  
# Project target.
target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-badge/dev-badge.gradle
cordova.system.library.1=com.android.support:customtabs:27.1.1
cordova.gradle.include.2=cordova-plugin-browsertab/dev-BrowserTab.gradle
cordova.gradle.include.3=cordova-plugin-buildinfo/dev-BuildInfo.gradle
cordova.gradle.include.4=cordova-support-google-services/dev-build.gradle
cordova.system.library.2=com.google.firebase:firebase-core:16.0.+
cordova.system.library.3=com.google.firebase:firebase-messaging:18.0.+
cordova.system.library.4=com.android.support:support-compat:26.1
cordova.system.library.5=me.leolin:ShortcutBadger:1.1.22@aar

```

Any adivce would be appreciated

**Comment by mmikrut** [comment]
Additional comment.
Just switched to cordova-plugin-fcm-with-dependecy-updated
Simlar test code generates token correctly.

**Comment by jordanorc** [comment]
Same error here... There is any workaround for this?

**Comment by elcheshoro** [comment]
Same. How are people getting around this?

**Comment by erellsworth** [comment]
I'm having this issue as well. It was working fine last week (last build was 6 days ago). Google released 2 updates to the firebase SDK since then, so I'm guessing that's why this just started.

https://firebase.google.com/support/releases#sdk_releases

**Comment by nfacha** [comment]
Also getting this error

**Comment by erellsworth** [comment]
For me it seems to be related to AndroidX. When this plugin updated to use AndroidX it broke because of some other plugins I have that use the older support libraries. To fix it I used the cordova-plugin-androidx and cordova-plugin-androidx-adapter. That was working but now it seems to be somehow causing the FirebaseApp is not initialized error.

I can't currently remove the other plugins, and I haven't found a fix for this yet.

**Comment by nfacha** [comment]
Found this fork, might work:
https://github.com/elcheshoro/cordova-plugin-firebase-messaging/commit/06a0f28b3e3a2a2ddeaaa192a4f202f9ad01bb25

**Comment by prashantagrawal17** [comment]
![firebasePluginIssueFirebaseAppNotinitializing](https://user-images.githubusercontent.com/756773/75168211-880e7000-574c-11ea-9134-788904ef765c.png)

me too having the same issue, "FirebaseApp" initialization issue after on app start (tested post Platform.ready() event).

**Comment by prashantagrawal17** [comment]
![firebasePluginIssueFirebaseAppNotinitializing _LI](https://user-images.githubusercontent.com/756773/75168686-5053f800-574d-11ea-9c7a-34fd36c11c20.jpg)
me too having the same issue, "FirebaseApp" initialization issue after on app start (tested post Platform.ready() event).
