### ISSUE TITLE
How to Implement onMessage?

### ISSUE THREAD

**Issue by satriasss** [chemerisuk/cordova-plugin-firebase-messaging#85]
Currently, I'm working in a project to use Push Notification on iOS and Android. However, we don't know how to implement the code properly. 

could you give me some advices ? 

this is our source code

`document.addEventListener("deviceready", onDeviceReady, false);
        function onDeviceReady() {
            cordova.plugins.firebase.messaging.onMessage(function(payload) {
                alert('hello');
                alert("New foreground FCM message: ", payload);
            });        
        }`
but, it doesnt work eventhough the notification has arrived on the device

Regards,

**Comment by tmk1991** [comment]
I think something is off with onMessage 

https://github.com/chemerisuk/cordova-plugin-firebase-messaging/issues/55#issuecomment-494983874

**Comment by tmk1991** [comment]
@satriasss  any luck?

**Comment by claudiulazar** [comment]
@satriasss @tmk1991 did someone manage to find something?

**Comment by romelgomez** [comment]
The README.md of the project has a example on how should to be set onMessage function  

```
cordova.plugins.firebase.messaging.onMessage(function(payload) {
    console.log("New foreground FCM message: ", payload);
});
```

other issues in this project mention this problem, I try it with two approach, no one single works 

```
(window as any).cordova.plugins.firebase.messaging.onMessage()
  .subscribe((payload: PushNotificationMessage) => {

    this.toastr.info(payload.notification.body, payload.notification.title);

  });

(window as any).cordova.plugins.firebase.messaging.onMessage(function (payload: PushNotificationMessage) {

  this.toastr.info(payload.notification.body, payload.notification.title);

});
```

The errors with sentry.io

**Cannot read property 'subscribe' of undefined** on the subscribe form


**Cannot read property 'firebase' of undefined** on the  callback form


This is  (window as any).cordova;

```


{
  "version": "8.1.0",
  "platformVersion": "8.1.0",
  "platformId": "android",
  "callbackId": 1662620561,
  "callbacks": {
    "CoreAndroid1662620554": {
      "fail": null
    },
    "CDVIonicKeyboard1662620558": {
      "fail": null
    }
  },
  "callbackStatus": {
    "NO_RESULT": 0,
    "OK": 1,
    "CLASS_NOT_FOUND_EXCEPTION": 2,
    "ILLEGAL_ACCESS_EXCEPTION": 3,
    "INSTANTIATION_EXCEPTION": 4,
    "MALFORMED_URL_EXCEPTION": 5,
    "IO_EXCEPTION": 6,
    "INVALID_ACTION": 7,
    "JSON_EXCEPTION": 8,
    "ERROR": 9
  },
  "file": {
    "applicationDirectory": "file:///android_asset/",
    "applicationStorageDirectory": "file:///data/user/0/com.cats/",
    "dataDirectory": "file:///data/user/0/com.cats/files/",
    "cacheDirectory": "file:///data/user/0/com.cats/cache/",
    "externalApplicationStorageDirectory": "file:///storage/emulated/0/Android/data/com.cats/",
    "externalDataDirectory": "file:///storage/emulated/0/Android/data/com.cats/files/",
    "externalCacheDirectory": "file:///storage/emulated/0/Android/data/com.cats/cache/",
    "externalRootDirectory": "file:///storage/emulated/0/",
    "tempDirectory": null,
    "syncedDataDirectory": null,
    "documentsDirectory": null,
    "sharedDirectory": null
  },
  "plugins": {
    "firebase": {
      "messaging": {}
    }
  }
}
```

   


https://github.com/chemerisuk/cordova-plugin-firebase-messaging/issues?utf8=%E2%9C%93&q=onMessage
