### ISSUE TITLE
Phonegap build and cordova-ios 5.0.0

### ISSUE THREAD

**Issue by josemolmomillan** [chemerisuk/cordova-plugin-firebase-messaging#86]
Hello

    I am using this plugin in one new app. I am using Phonegap Build where the higher cordova-ios=4.5.5. 
   From cordova-plugin-firebase-messaging 2.0.0 is using cordova-ios=5.0.0.

   could it be possible to use cordova-ios=4.5.5 with the current version of plugin?

   do you know some guy using phonegap build with this plugin on iOS platform?

Thanks

**Comment by chemerisuk** [comment]
In version 2.1+ I use `<podspec>` tag in `plugin.xml` that supported only in cordova-ios>=5.0.0.
If you use cordova-ios=4.5.5 try to install version 1:
```
cordova plugin add cordova-plugin-firebase-messaging@^1
```

**Comment by josemolmomillan** [comment]
I have also tried it, but i am getting this error in my phonegap build logs, and I am lost right now

plugman-151 install --platform ios --project /project --plugin cordova-plugin-firebase-messaging@1.4.0 --nohooks=. ": Fetching plugin "cordova-plugin-firebase-messaging@1.4.0" via npm
Installing "cordova-plugin-firebase-messaging" at "1.4.0" for ios
Failed to install 'cordova-plugin-firebase-messaging': Error: pod: Command failed with exit code 1
   at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
   at ChildProcess.emit (events.js:182:13)
   at maybeClose (internal/child_process.js:962:16)
   at Socket.stream.socket.on (internal/child_process.js:381:11)
   at Socket.emit (events.js:182:13)
   at Pipe._handle.close (net.js:611:12)
pod: Command failed with exit code 1

I need to use Phonegap Build because I dont have any Mac. I guess this error is about cocoapods update, but I don't know how to force pods updates  in Phonegap builder. do you?

Thanks

**Comment by chemerisuk** [comment]
@josemolmomillan try `cd platforms/ios && pod update`

**Comment by WallioApp** [comment]
I am getting same error:
Failed to install 'cordova-plugin-firebase-messaging': Error: pod: Command failed with exit code 1
at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
at ChildProcess.emit (events.js:182:13)

When building with Ionic AppFlow (similar to Phonegap build?).
I did try these but no luck:
https://ionic.zendesk.com/hc/en-us/articles/360010049673-Managing-plugins-using-CocoaPods-in-Ionic-Appflow-

Ionic support sends to Maks for the fix :-). Can you help us out here? Please :-)

**Comment by WallioApp** [comment]
For the record, I fixed AppFlow build by following instructions here:
https://ionic.zendesk.com/hc/en-us/articles/360010049673-Managing-plugins-using-cocoapods-in-Ionic-Pro

"pod repo update"  is a culprit.
Make sure Step 3 is executed. In my case scripts (step 1 and step 2) were not throwing any permission errors and I was mistakenly assuming scripts execute successfully. However, scripts were not failing nor executing! Executing Step 3 and granting permissions as described, solved the problem and now I can compile iOS build without Mac :-)

**Comment by chemerisuk** [comment]
Phonegap is deprecated now.
