### ISSUE TITLE
iOS not getting messages in background

### ISSUE THREAD

**Issue by StevenRodz** [chemerisuk/cordova-plugin-firebase-messaging#87]
This is more of a question than an issue. Perhaps I missed a step, but iOS receives all messages in the foreground perfectly, but not in the foreground. Is there somewhere where I can find the installation steps for iOS to ensure I did not miss something? It is running smoothly on Android.

**Comment by StevenRodz** [comment]
This problem happened to me on a device with iOS 9, however, a device with iOS 12 had no issue. I don't know about support for 10 and 11. Can you provide info on this?

**Comment by chemerisuk** [comment]
iOS 9 is not supported by Cordova.
