### ISSUE TITLE
Using "requireCordovaModule" to load non-cordova module "glob" is not supported.

### ISSUE THREAD

**Issue by uncvrd** [chemerisuk/cordova-plugin-firebase-messaging#89]
Hi! Thanks for managing this plugin :) So with the new update, you force Cordova to use V9. Which is great, because you use the `podspec` to add pods, however, they depreciated something in the major release of v9 that I guess this plugin still uses. Here is the error that I receive when attempting to add this plugin to my project:

`Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.`

Here is the related issue request where a Cordova dev indicates, that projects will need to be updated because v9 brought about some breaking changes related to the `requireCordovaModule`:

https://github.com/apache/cordova-cli/issues/416#issuecomment-478306606'

I am using Ionic, and here are the specs I am attempting to use:
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.12.2
   @angular-devkit/schematics    : 7.2.2
   @angular/cli                  : 7.2.2
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.1, (and 17 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS
   Xcode      : Xcode 10.2.1 Build version 10E1001
```

**Comment by chemerisuk** [comment]
This plugin does not have any cordova hooks.
