### ISSUE TITLE
google-services.json is missing

### ISSUE THREAD

**Issue by fmoyota** [chemerisuk/cordova-plugin-firebase-messaging#9]
Hi 
I try to build with phonegap build. 
Android build fail, I get This message:

File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /project/src/release/google-services.json
  /project/google-services.json

I downloaded and put the correct google-service.json file from firebase in root directory on my project.
I created the directories 
/project/src/release/google-services.json
/project/google-services.json 

on root directory but the issue keeps

I build project with phonegap version 6.5.0 and 7.0.1

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-support-google-services#installation
