### ISSUE TITLE
Notification does not receive on Android

### ISSUE THREAD

**Issue by girishk55** [chemerisuk/cordova-plugin-firebase-messaging#90]
Push notification does not receive on android platform but working on iOS. getToken and onMessage function get fired but the token and payload is blank. 

Can you please help in this.

**Comment by girishk55** [comment]
Any help will be appreciated to solve this issue on Android platform.

**Comment by odai-alali** [comment]
Check the generated `AndroidManifest.xml`. If you are using `cordova-cli@9.0.0` then the problem might be in merging the configurations. by me

```xml
<service android:name="by.chemerisuk.cordova.firebase.FirebaseMessagingPluginService">
                <intent-filter>
                    <action android:name="com.google.firebase.MESSAGING_EVENT"/>
                </intent-filter>
            </service>
```

was missing from the manifest file.

**Comment by girishk55** [comment]
hi @odai-alali, I am using 9.0.0 (cordova-lib@9.0.1) the configuration is already available in manifest file, still not getting push notification. getToken and onMessage function get fired but the token and payload is blank.

**Comment by odai-alali** [comment]
Then you have another problem. Hope you find a solution

**Comment by wasimbakali** [comment]
I'm having the same issue, in ionic@3.9.3 and cordova@10.0.0 and cordova-android@9.0.0

**Comment by haresh333** [comment]
> I'm having the same issue, in ionic@3.9.2 and cordova@10.0.0 and cordova-android@9.0.0

Did you find any solution
I have same configuration as yours
