### ISSUE TITLE
Android 8 and higher (API > 26) - Failed to post notification on channel null

### ISSUE THREAD

**Issue by jordanorc** [chemerisuk/cordova-plugin-firebase-messaging#91]
I'm getting a message "failed to post notification on channel null" on android 8 and higher. Documentation indicates we need to configure a "default_notification_channel_id" (https://github.com/chemerisuk/cordova-plugin-firebase-messaging#set-custom-default-notification-channel), but that is still required to create a notification channel in code. How can I create a notification channel in code if the plugin does not provide methods to do that? Someone know a workaround for this?

**Comment by chemerisuk** [comment]
Fixed in v4
