### ISSUE TITLE
onMessage() not firing on iOS

### ISSUE THREAD

**Issue by RenatoSilveiraGomes** [chemerisuk/cordova-plugin-firebase-messaging#95]
On iOS, when the App is in the background (fully closed), the onBackgroundMessage() is fired as expected, but when is just minimized doesn't. And, when the App is in the foreground, onMessage() is never fired. I used requestPermission({ forceShow: true }).

Can anyone help me, please? Thank you very much!

**Comment by RenatoSilveiraGomes** [comment]
On Android it's all working as expected.

**Comment by themightydeity** [comment]
Hey I ran into similar issue, then I checked through Safari's inspector, there were some error about cordova-plugin-firebase-messaging plugin being missing in the console. But I had it installed.

The fix for this is basically until device is ready (platform.ready) in iOS the firebase plugin is not loaded, so you need to move your onBackgroundMessage and onMessage inside this.platform.ready

**Comment by claudiulazar** [comment]
@RenatoSilveiraGomes when you call 
```requestPermission({ forceShow: true })```
or
```requestPermission()```
1 - does this trigger the request for notification popup?
2 - does what does this function return for you ?

---------------------------------------------------------------------------
@themightydeity  I called the requestPermission in the platform.ready retured promise method and still nothing, the will trigger prompt isn't showing on iOS.
can you share the chunk of code regarding this?

**Comment by nabil-nuvolo** [comment]
I am also experiencing this issue, `showMessage` is not firing when recieiving push notifications in the foreground. 

Additionally, `requestPermission` with `forceShow` does not prompt me on my device and returns a `null` result.

**Comment by themightydeity** [comment]
> @RenatoSilveiraGomes when you call
> `requestPermission({ forceShow: true })`
> or
> `requestPermission()`
> 1 - does this trigger the request for notification popup?
> 2 - does what does this function return for you ?
> 
> @themightydeity I called the requestPermission in the platform.ready retured promise method and still nothing, the will trigger prompt isn't showing on iOS.
> can you share the chunk of code regarding this?

@claudiulazar I am receiving the request for permission notification popup in iOS.


I am using ionic-native, here is corodva section in my package.json :

```
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-appminimize": {},
      "cordova-plugin-androidx-adapter": {},
      "cordova-plugin-firebase-messaging": {},
      "cordova-support-google-services": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      }
    },
    "platforms": [
      "ios",
      "browser",
      "android"
    ]
  }
```

this is the part I have in platform.ready, typescript code from my  ionic-native project

```
    this.platform.ready().then(() => {
        ...
        this.firebase.onMessage().subscribe(()=>{
            ...
        });
        this.firebase.onBackgroundMessage().subscribe(()=>{
            ...
        });
        ...
        this.firebase.requestPermission().then(() => {
            ...
            this.firebase.getToken().then((token: string) => {
                ...
            }).catch((error) => {
                ...
            });
        }).catch((error) => {
            ...
        });
    });
```

**Comment by mathew-n27** [comment]
Same here, onMessage is not firing when receiving push notifications in the foreground.

Also `requestPermission({forceShow: true})` returns a `null`.

Using Cordova 8, ios 5.0.1

Any help will be much appreciated.

**Comment by gbarnett** [comment]
Also encountering this issue. onMessage() and onBackroundMessage not being called on iOS

**Comment by themightydeity** [comment]
@mathew-n27 
I am using cordova 9.0.0 (cordova-lib@9.0.1) and I think these are the most relevant part in my package.json for firebase  to work. 

```
"cordova-ios": "^5.0.1",
"cordova-plugin-androidx-adapter": "^1.1.0",
"cordova-plugin-firebase-messaging": "^3.0.0",

```

@gbarnett  and @mathew-n27  I hope you guys have done all the setup required for iOS push notification development.

**Comment by mathew-n27** [comment]
@themightydeity Yes, all iOS requirements fulfilled.

**Comment by fluxc** [comment]
I have been having this problem as well, I've tried all of the above and in different variations but still no luck, any ideas?

**Comment by dogofpavlov** [comment]
Same issue, onMessage is not firing :(. Does work for Android.

**Comment by DmytroKurapin** [comment]
@dogofpavlov  Try to add **content-available: 1** or **contentAvailable: true** to each your  notification message. Started to work for me

**Comment by dogofpavlov** [comment]
@DmytroKurapin thanks, though I ended up going with the phonegap push plugin and didn't have to change anything. Glad works for you though :D

**Comment by mathew-n27** [comment]
Thanks @DmytroKurapin `content_available: 1` did the trick.

**Comment by chemerisuk** [comment]
Flag `content_available` required on iOS in order to handle ANY callback in ANY native plugin. Otherwise it won't work. I'll update README, but still strongly recommend to read APNS and FCM protocol specs.

**Comment by DuaneQ** [comment]
> @dogofpavlov Try to add **content_available: 1** or **contentAvailable: true** to each your notification message. Started to work for me

@chemerisuk 

could either of you provide an example of how content_available is implemented?  Should this be apart of the message payload:

example:
`    const payload = {
        notification: {
            title: 'New message',
            body: `${content}`,
            click_action: 'FCM_PLUGIN_ACTIVITY'
        },
        data: {
            page: 'tabs/travel-buddies',
        }
    };`

**Comment by dileepjb2** [comment]
contentAvailable: true works for me but firing both foreground and background notifications
