### ISSUE TITLE
Getting "Object(i.cordova) is not a function" error when using plugin methods

### ISSUE THREAD

**Issue by thwbs** [chemerisuk/cordova-plugin-firebase-messaging#99]
When I use any of the plugin methods I get this error (example is with using requestPermission):

Error: Uncaught (in promise): TypeError: Object(i.cordova) is not a function. (In 'Object(i.cordova)(this,"requestPermission",{sync:!0},arguments)', 'Object(i.cordova)' is an instance of Object) requestPermission@http://localhost:8080/var/containers/Bundle/Application/598CB4D5-650D-4284-88E6-DF9FF2474B2F/News.app/www/build/vendor.js:1:1332446 continueStartingUp@http://localhost:8080/var/containers/Bundle/Application/598CB4D5-650D-4284-88E6-DF9FF2474B2F/News.app/www/build/main.js:1:1184580 http://localhost:8080/var/containers/Bundle/Application/598CB4D5-650D-4284-88E6-DF9FF2474B2F/News.app/www/build/main.js:1:1183675 onInvoke@http://localhost:8080/var/containers/Bundle/Application/598CB4D5-650D-4284-88E6-DF9FF2474B2F/News.app/www/build/vendor.js:1:81558 run@http://localhost:8080/var/containers/Bundle/Application/598CB4D5-650D-4284-88E6-DF9FF2474B2F/News.app/www/build/polyfills.js:3:10149 http://localhost:8080/var/containers/Bundle/Application/598CB4D5-650D-4284-88E6-DF9FF2474B2F/News.app/www/build/polyfills.js:3:20245 onInvokeTask@http://localhost:8080/var/containers/Bundle/Application/598CB4D5-650D-4284-88E6-DF9FF2474B2F/News.app/www/build/vendor.js:1:81476 runTask@http://localhost:8080/var/containers/Bundle/Application/598CB4D5-650D-4284-88E6-DF9FF2474B2F/News.app/www/build/polyfills.js:3:10844 o@http://localhost:8080/var/containers/Bundle/Application/598CB4D5-650D-4284-88E6-DF9FF2474B2F/News.app/www/build/polyfills.js:3:7901 invokeTask@http://localhost:8080/var/containers/Bundle/Application/598CB4D5-650D-4284-88E6-DF9FF2474B2F/News.app/www/build/polyfills.js:3:16824 n@http://localhost:8080/var/containers/Bundle/Application/598CB4D5-650D-4284-88E6-DF9FF2474B2F/News.app/www/build/polyfills.js:3:66

I use the Ionic platform, testing it on an ios device, and using Safari for debugging

Here is what I get running "ionic info":

Ionic:
   Ionic CLI          : 5.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 19 other plugins)

Utility:
   cordova-res : not installed
   native-run  : 0.2.6 (update available: 0.2.7)

System:
   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.16.0 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001 

**cordova info:**

cordova-lib@9.0.1 with:
  cordova-common@3.2.0
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment: 
  OS: darwin
  Node: v10.16.0
  npm: 6.9.0

Plugins:
  com-sarriaroman-photoviewer
  cordova-background-geolocation
  cordova-open-native-settings
  cordova-plugin-app-version
  cordova-plugin-background-fetch
  cordova-plugin-camera
  cordova-plugin-cocoalumberjack
  cordova-plugin-device
  cordova-plugin-file
  cordova-plugin-file-transfer
  cordova-plugin-firebase-messaging
  cordova-plugin-inappbrowser
  cordova-plugin-ionic-keyboard
  cordova-plugin-ionic-webview
  cordova-plugin-network-information
  cordova-plugin-splashscreen
  cordova-plugin-statusbar
  cordova-plugin-streaming-media
  cordova-plugin-whitelist
  cordova-sqlite-storage
  cordova-support-google-services
  phonegap-plugin-barcodescanner
  sentry-cordova

iOS platform:
  Xcode 10.2.1
  Build version 10E1001

**Comment by DiegoMasc** [comment]
same error i am getting 
vendor.js:2085 ERROR TypeError: Object(...) is not a function
    at FirebaseMessaging

but i am correctly using cordova-plugin-firebase-authentication  and cordova-support-google-services

**Comment by DiegoMasc** [comment]
solved downgrading to v4
npm install --save @ionic-native/firebase-messagging@4
